### ISSUE TITLE
Use template for API conf

### ISSUE THREAD

**Issue by downingar** [nginxinc/ansible-role-nginx#108]
It would be useful to be able to switch the template used for the API configuration, for instance restricting what IPs are allowed to access the API. I have a PR to go along with this issue I wasn't sure exactly where to put the API template, so I threw it in the top level of the templates dir.

**Comment by gdzien** [comment]
Hello,

Thank you for your contribution! We have agreed that your PR looks good, and it is now merged to the role.

Sincerely,
Grzegorz Dzień
