### ISSUE TITLE
support for ngx_http_auth_request_module

### ISSUE THREAD

**Issue by coreaut** [nginxinc/ansible-role-nginx#120]
Hi I wan't to configure something like this,

but currently the auth_request module is not supported.

```code
# Any request to this server will first be sent to this URL
auth_request /validate;

location = /validate {
  proxy_pass http://127.0.0.1:9090/validate;
  proxy_pass_request_body off; # no need to send the POST body

  proxy_set_header Content-Length "";
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;

}

error_page 401 = @error401;

# If the user is not logged in, redirect them to Lasso's login URL
location @error401 {
  return 302 https://sso.somehost.local/?url=https://$http_host$request_uri;
}
```

Do you consider to integrate the support for auth_request?

Other than that, your role is really nice!

**Comment by magicalyak** [comment]
@coreaut I just pushed a PR but need it tested, I would test this on something where you can handle it not working but it should take in the configuration you specified.
This assumes the module is already in NGINX (Plus has this by default)

**Comment by magicalyak** [comment]
@coreaut hold on a little bit, something isn't right on the template part, will push changes again shortly

**Comment by magicalyak** [comment]
Ready to test now or merge

**Comment by magicalyak** [comment]
@alessfg can we close this?
