### ISSUE TITLE
Add tag option for controller

### ISSUE THREAD

**Issue by magicalyak** [nginxinc/ansible-role-nginx#124]
I think it’s possible to add a tag when we add the instance to controller. I plan to submit a pr for this. 
1) would like an option to add tag(s) to the controller agent

**Comment by magicalyak** [comment]
I need to check if the installer supports this.  May be an impossible ask.

**Comment by magicalyak** [comment]
This is supported, they can be added in the agent.conf like this (since 1.0.0)

[tags]
tags = foo,bar,foo:bar

**Comment by alessfg** [comment]
Tags have been added to all major functionalities in the role.
