### ISSUE TITLE
Is it possible to specify the desired version of nginx?

### ISSUE THREAD

**Issue by glauberferreira** [nginxinc/ansible-role-nginx#132]
I am using this role for managing Ubuntu Bionic machine. When I executed this role for the first time, nginx/1.15.12 was installed by the role. Now, executing the role again (with the new mainline nginx-1.17.0 released), nginx is not being upgraded. Should I upgraded manually, using a `pre_task`?

**Comment by alessfg** [comment]
Hi @glauberferreira! 

Right now there's no way to specify the version of NGINX to be installed, same with upgrading the version of NGINX (to do this you can either manually upgrade NGINX or uninstall NGINX and run the role again). 

Adding an option to upgrade NGINX is on the backlog (not so much the option to specify the version of NGINX to be installed), and a PR implementing that option would be more than welcome!

Cheers,
Alessandro.
