### ISSUE TITLE
Cannot specify ssl_password_file option

### ISSUE THREAD

**Issue by vladp** [nginxinc/ansible-role-nginx#134]
There are seem to be no way to specify ssl_password_file option in server configuration.

That means that the file containing private key must be un-encrypted.

Is there a workaround (without modifying default templates that come with this role)?

thank you

**Comment by alessfg** [comment]
Hi @vladp!

You can upload your own NGINX configuration file using the `nginx_http_upload_*` parameters (https://github.com/nginxinc/ansible-role-nginx/blob/master/defaults/main.yml#L105). You are also more than welcome to submit a PR adding the parameter to the default template 😄 

Cheers,
Alessandro.

**Comment by vladp** [comment]
thank you. will leverage the nginx_http_upload
