### ISSUE TITLE
Some standard modules are not avialable on all supported Platforms

### ISSUE THREAD

**Issue by vladp** [nginxinc/ansible-role-nginx#135]
getting below error
Using ansible 2.8,  Target host is is:  FreeBSD 12.

```
 FAILED! => {"changed": false, "msg": "failed to install nginx-module-geoip: ", │
"stderr": "pkg: No packages available to install matching 'nginx-module-geoip' have been found in the repositories│                        custom_var_for_this_host: myblahcustomvar
\n", "stderr_lines": ["pkg: No packages available to install matching 'nginx-module-geoip' have been found in the │                     host01 :  #this api uses fs_metadata 
repositories"]}                                                                                                   │                        ansible_port: 11022
```

I also tried to install nginx with same geoip module on OpenBSD 6.5 -- similar problem module is not found.

**Comment by alessfg** [comment]
Thanks for creating this issue! 

I think this is happening because all modules are installed using Ansible's `package` module, but to work with NGINX in FreeBSD you need to use ports and the `portinstall` module. 

Let me do some further research. If my initial thoughts are correct it should be a relatively easy fix.

Cheers,
Alessandro.

**Comment by alessfg** [comment]
So, on FreeBSD, when you install the default `nginx` port you choose which modules to install when running `make`. Doing this in an automated way is not trivial, with the best solution probably being to implement a way to create a build options file at runtime that then gets read when building the `nginx` port.

Alternatively, for now, a workaround would be to manually modify the value at https://github.com/nginxinc/ansible-role-nginx/blob/master/tasks/opensource/install-oss.yml#L26 from `nginx` to `nginx-full`, and not enable modules on the role. The `nginx-full` port builds pretty much all modules, which you should then be able to normally load from your NGINX configuration file.

**Comment by vladp** [comment]
since this role uses nginx packag from your repository, would it be possible get your repository to host all the binaries of plugins for a given os (eg freebsd, openbsd) and then the role would pull out of there?
Meaning that you would have to build it (using the ports tree, as you noted, but then host the resulting packages). This way individual users do not have to build it.

(sorry if I am misunderstanding this).

**Comment by alessfg** [comment]
In FreeBSD the NGINX open source packages are hosted in the ports collection, and that's something that I do not foresee will change in the foreseeable future. There's some potential fixes, like I mentioned in the previous comment, but it'll take some time before a decision is made about how to best proceed.

**Comment by vladp** [comment]
ah, ok. I understand now. Basically for FreeBSD (and openBSD) this role, will actually build nginx on the target host.

**Comment by vladp** [comment]
Your workaround also helped me to solve:  uknown directive 'stream' error.
That I was getting on FreeBSD 12.

Installing nginx-full on FreeBSD seems to be a requirement overall, because the 'stream' module is also not avialable in 'nginx' standard build (the stream module is assumed to be available in the role -- because it allows to specify `stream_enable`    option)

**Comment by alessfg** [comment]
Sorry for all the trouble you are running into @vladp. FreeBSD support is still very much in an early development phase, so thanks for bearing with us!

That is a very interesting find indeed too, it may be worth changing the default port to `nginx-full` in that case, at least for the time being.

**Comment by vladp** [comment]
Thank you, yes -- it seems that doing nginx-full for FreeBSD would solve lots of the module issues.
The trouble for me was that when building nginx-full from Ports, it seems that lots of packages needed to be installed prior to that port to build.  

Normally FreeBSD would download recursively the source for packages it needed, but it did not (so first it was missing ImageMagick6, then when installed it using package module, it started complaining that apache24 needed to be installed... and so on).

Overall it meant that  either package system was not working to figure out source dependencies, recursively... or something else.  Plus, I realized, that nginx-full requires so many depedencies (including X system, wayland) -- that it would take hours if not a day to building nginx-full and resulting system (at least in my case would run out of space allocated for the target host).

Which is why, I thought, that if nginx-full was, indeed,  needed -- it had to come from a binary package (eg using ' `pkg install nginx-full`' from FreeBSD official binary package repol (or may be you repo in the future ) -- rather than building it.

**Comment by alessfg** [comment]
Oh I see. Well, you can always install NGINX from FreeBSD's package repository, but it tends to be a couple versions behind mainline. Nonetheless (#87) also adds the option to choose between a ports or package install. Hopefully that should add more options.

**Comment by vbotka** [comment]
> Which is why, I thought, that if nginx-full was, indeed, needed -- it had to come from a binary package (eg using ' `pkg install nginx-full`' from FreeBSD official binary package repol (or may be you repo in the future ) -- rather than building it.

FWIW. Use *portinstall/portupgrade*. This will install the dependencies and will use packages if available.
``portinstall --upward-recursive --use-packages www/nginx-full``

**Comment by alessfg** [comment]
The latest release (0.13.0) should address this issue. Feel free to reopen the issue if it's still not working!
