### ISSUE TITLE
Websockets part in http template is missing.

### ISSUE THREAD

**Issue by shokinn** [nginxinc/ansible-role-nginx#139]
Hey there,
is there a reason why the websockets configuration part which was added in 8db44bf97905bb100d69123d3e1c205bc8ea3661 was removed in 783d29639cce0a931589e67a1e2cb938b74dd1ef?

The option for the websocket configuration part is still shown in the README.md and also configured in the defaults/main.yml.

If it was a mistake that it is gone, should I file a PR to get it back to the template?

**Comment by alessfg** [comment]
It was definitely a mistake that somehow slipped through code review 😕 

Please file a PR!

**Comment by alessfg** [comment]
This issue was fixed by #140. Thanks @shokinn for your contributions!
