### ISSUE TITLE
IPv6 listener missing

### ISSUE THREAD

**Issue by shokinn** [nginxinc/ansible-role-nginx#146]
Hey there,
there is no IPv6 listener like `listen [::]:443 ipv6only=on ssl;` is this behavior expected or is this a bug?
If yes should we add the IPv6 listen directives and make both IPv4 and IPv6 configurable to switch them on or off independently?

I also like to know if it could be a good idea to make the listen options like `ssl`, `ipv6only=on` or `http2` configurable.

```
root@dev /etc/nginx # netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      23337/nginx: master
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      703/systemd-resolve
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1042/sshd
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      23337/nginx: master
tcp6       0      0 :::22                   :::*                    LISTEN      1042/sshd
tcp6       0      0 :::2376                 :::*                    LISTEN      1453/dockerd
udp        0      0 127.0.0.53:53           0.0.0.0:*                           703/systemd-resolve
udp        0      0 0.0.0.0:68              0.0.0.0:*                           726/dhclient
```

**Comment by alessfg** [comment]
New directives/templating options have been added as feature requests for the most part. IPv6 support hasn't come up till now 😄 

Re listen options -- the `ssl` option is already implemented, but it would definitely be a good idea to implement support for as many other listen options as possible. #85 did some work on adding parameters to the listen directive but that PR sadly never went anywhere.

**Comment by sangdrax8** [comment]
I could also use the ability to add http2 listen option.

**Comment by alessfg** [comment]
Support for various listen directives has been added in #147!
