### ISSUE TITLE
access_log - error_log per vhost

### ISSUE THREAD

**Issue by bogomips** [nginxinc/ansible-role-nginx#152]
Hello,
it seems like access_log and error_log are not in the template, 
Is there an official way to customize those parameters per each vhost?

Thanks

**Comment by bogomips** [comment]
If this can help someone, I ended up with changing the template like this
```{% if item.value.error_page is defined %}
    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   {{ item.value.error_page }};
    }

{% if item.value.access_log is defined %}
    access_log {{ item.value.access_log }};
{% endif %}
{% if item.value.error_log is defined %}
    error_log {{ item.value.error_log }};
{% endif %} 

{% endif %}
}```

then from the vars:

```
 my_host:
            template_file: http/default.conf.j2
            conf_file_name: my_host.my_domain.tld.conf
            conf_file_location: /etc/nginx/conf.d/
            port: 82
            server_name: my_host.my_domain.tld
            error_page: /usr/share/nginx/html
            autoindex: false
            access_log: /var/log/nginx/my_host.my_domain.tld-access.log
            error_log: /var/log/nginxmy_host.my_domain.tld-error.log
            web_server:
               locations:
                  default:
                     location: /
                     html_file_location: /var/www/my_host.my_domain.tld
                     html_file_name: index.html
                     autoindex: false
               http_demo_conf: false

```

**Comment by alessfg** [comment]
Hi @bogomips!

`access_log` and `error_log` can be found on `templates/nginx.conf.j2`. However, they are not customizable at the moment. I'll start work on a PR to add it to the templating options.

Cheers,
Alessandro.
