### ISSUE TITLE
HTTPS redirect and multiple server names

### ISSUE THREAD

**Issue by xTrekStorex** [nginxinc/ansible-role-nginx#153]
When one sets multiple server names such as `mysite.dom 123.123.123.123` and uses `https_redirect: true` the template generates a broken config:

```
server {
    listen 80;
    server_name mysite.dom 123.123.123.123;
    return 301 https://mysite.dom 123.123.123.123$request_uri;

}
```

According to the template code https://github.com/nginxinc/ansible-role-nginx/blob/155c13c14058b3f86ca943882554af6c2240d1ab/templates/http/default.conf.j2#L91 it only uses `$host` when `_` is used for the server name. However in my experience using `_` in every vhost that maps to more than one server name is bad. Since it impacts the handling of non-matching requests by sending them to the first vhost with server name `_` in alphabetic order of the config files. So I personally only define one vhost with server name `_` per nginx instance.

Wouldn't it make more sense to always use `$host` in the redirect or at least also check server name for a space?

**Comment by alessfg** [comment]
Thanks for creating/catching this issue @xTrekStorex!

Re your suggestions, always using `$host` by default can become a limiting factor in more advanced configurations. However, you are right that using `server_name` is not necessarily the best way to make redirects work correctly, especially for use cases with multiple server names. I'm thinking of two different approaches. 

**Approach 1:** Only use the first server name for the redirect. 

**Approach 2:** Let users configure the redirect target as a variable.

Out of these two, I think the later is the best approach. It removes a tiny layer of automation from the role by having users manually configure the redirect, but it provides the most customization, and at some stage, may tie into further `return` templating options.

Thoughts?

**Comment by xTrekStorex** [comment]
While I always prefer shorter configurations and thus also short plays, I think having the redirect target as a variable is worth adding the extra line. 

I personally would be fine with configuring it indirectly by changing the order of my server names as required or even adding a name in front that would never reach the server as a request (local IP ranges etc.), but a variable would be cleaner and also improves readability.

**Comment by shokinn** [comment]
How about to use the current behavior if the variable is not defined like in Approach 2 from @alessfg suggested?
In the code it would be just an if more.

**Comment by magicalyak** [comment]
I can test if this would work for now (should use first item)
{{ item.value.server_name | first }}
I don't know if that would fail on a single list but could test this out.

**Comment by alessfg** [comment]
For the time being I am going to let users define the target redirect host. Removes some automation from the role but it lets users customize the `https_redirect` behaviour way better.
