### ISSUE TITLE
error while running playbook on amazon-2 linux

### ISSUE THREAD

**Issue by amolkhanorkar** [nginxinc/ansible-role-nginx#166]
"msg": "Failure talking to yum: failure: repodata/repomd.xml from nginx: [Errno 256] No more mirrors to try.\nhttps://nginx.org/packages/mainline/centos/2/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found"

Please help me solving this issue

**Comment by alessfg** [comment]
Hi @amolkhanorkar - Amazon Linux 2 is not a supported platform for NGINX Open Source. Sorry about that.
