### ISSUE TITLE
nginx_http_upload_src doesn't work with relative path

### ISSUE THREAD

**Issue by tmvcode** [nginxinc/ansible-role-nginx#170]
Hi @lunarthegrey!

Sorry for the late reply! I've been trying to replicate your issue but everything seems to be working on my end. 

From what I can see, you are installing the role from Ansible Galaxy. If that is the case, and you wish to use `nginx_http_upload_src: conf/http/*.conf` you will have to include the files in `/home/user/.ansible/roles/nginxinc.nginx/files/conf/http`. By default, if you only provide a file name (eg `conf/http/*.conf` vs ./conf/http/*.conf`) the `copy` module looks for files located in the role `files` directory.

Alternatively, you can use a full path (as you've already discovered), or set a relative path (`../*.conf`) -- in the latter case Ansible will try to find the files at a location relative to the location of the Ansible playbook being deployed (not the role install location).

Let me know if that helps!

Cheers,
Alessandro.

_Originally posted by @alessfg in https://github.com/nginxinc/ansible-role-nginx/issues/123#issuecomment-492321596_

**Comment by tiepvo** [comment]
Hi Alessandro,

As you can see, the configuration for nginx_http_upload_src and nginx_stream_upload_src operates differently but declared similarly which makes it confusing.  The workaround is to declared nginx_stream_upload_src using absolute path.

[//]: # Upload HTTP NGINX configuration files.
nginx_http_upload_enable: true
nginx_http_upload_src: ./conf/http/*.conf
nginx_http_upload_dest: /etc/nginx/conf.d/http/

[//]: # Upload Stream NGINX configuration files.
nginx_stream_upload_enable: true
nginx_stream_upload_src: ./conf/tcp/*.conf
nginx_stream_upload_dest: /etc/nginx/conf.d/tcp/


```
tmv@xxx:~/work/ansible/nginx$ tree
.
|-- conf
|   |-- http
|   |   `-- tmv-http.conf
|   |-- nginx.conf
|   `-- tcp
|       `-- tmv-tcp.conf
|-- hosts
`-- playbook.yml

```

`tmv@xxx:~/work/ansible$ ansible-playbook -vvv -i nginx/hosts nginx/playbook.yml`
[//]: # wrong behavior since it picked up the wrong file tmv-http-role-location.conf in the role directory instead of tmv-http.conf file which is relatively declared in nginx_stream_upload_src
changed: [yyy] => (item=/home/tmv/work/ansible/roles/nginxinc.nginx/files/./conf/http/tmv-http-role-location.conf) => {...

[//]: # this is the expected behavior for nginx_stream_upload_src when declared relatively to the location of playbook.yml
changed: [yyy] => (item=/home/tmv/work/ansible/nginx/./conf/tcp/tmv-tcp.conf) => {...

**Comment by alessfg** [comment]
Can you provide some more information @tmvcode? It'd be helpful to see your playbook and full `playbook.yml`, and where is the NGINX role installed? For what is worth, both `nginx_http_upload_src` and `nginx_stream_upload_src` operate exactly the same way (you can see the code at https://github.com/nginxinc/ansible-role-nginx/blob/0.12.0/tasks/conf/upload-config.yml#L16-L44).

**Comment by tmvcode** [comment]
```
/home/tmv/work/ansible$ ls
ansible.cfg     nginx           roles

/home/tmv/work/ansible$ cat ansible.cfg
[defaults]
roles_path = ./roles

/home/tmv/work/ansible$ ls roles
nginxinc.nginx

/home/tmv/work/ansible$ cat nginx/playbook.yml
---
- hosts: dev
  become: yes

  tasks:
  - include_role:
      name: nginxinc.nginx
    vars:
      # Upload the main NGINX configuration file.
      nginx_main_upload_enable: true
      nginx_main_upload_src: ./conf/nginx.conf
      nginx_main_upload_dest: /etc/nginx/
      # Upload HTTP NGINX configuration files.
      nginx_http_upload_enable: true
      nginx_http_upload_src: ./conf/http/*.conf
      nginx_http_upload_dest: /etc/nginx/conf.d/http/
      # Upload Stream NGINX configuration files.
      nginx_stream_upload_enable: true
      nginx_stream_upload_src: ./conf/tcp/*.conf
      nginx_stream_upload_dest: /etc/nginx/conf.d/tcp/

/home/tmv/work/ansible$ ansible-playbook -vvv -i nginx/hosts nginx/playbook.yml
```

**Comment by alessfg** [comment]
Do you still get the same error if you run the playbooks from inside the `nginx` folder (`ansible-playbook -vvv -i hosts playbook.yml`)?

**Comment by tmvcode** [comment]
Yes, same error if I run the playbook inside the nginx folder.  In order to run inside the nginx folder, I placed the roles folder under the nginx folder.  The result is the same, it looked for the wrong file the role folder.

```
changed: [aquarius] => (item=/home/tmv/work/ansible/nginx/roles/nginxinc.nginx/files/./conf/http/tmv-http-role-location.conf) => {
    "ansible_loop_var": "item", 
    "changed": true, 
    "checksum": "9585c051fc1eea94459e19c13d23696f94be6f71", 
    "dest": "/etc/nginx/conf.d/http/tmv-http-role-location.conf", 

```

**Comment by tmvcode** [comment]
[nginx.tar.gz](https://github.com/nginxinc/ansible-role-nginx/files/3745316/nginx.tar.gz)

I uploaded my the nginx folder for you to replicate.

**Comment by alessfg** [comment]
Thanks for sharing your config! I've identified the issue 😄 

Namely, when you use a relative path, the first path that Ansible searches is the roles' file path. In this case, there's a pre-existing `files/conf/http` path (which also happens to be the recommended location for any HTTP configuration files you may want to upload -- although that's only a recommendation :p). What this means is that Ansible partially matches that path and by the looks of Ansible ends up doing a weird lookup for that path (not entirely sure why).

I've tested changing `nginx_http_upload_src: ./conf/http/*.conf` to `nginx_http_upload_src: ./conf/foo/*.conf` and that change seems to have fixed the issue.

I recommend checking out https://stackoverflow.com/questions/46065999/resolve-local-files-by-playbook-directory for some additional information on how Ansible does path lookups for relative paths.

**Comment by tmvcode** [comment]
Great job @allesfg!  I was able to confirm your resolution.  Thank you for your finding.

**Comment by alister** [comment]
I've just spent more than an hour trying to find the correct configuration to have files uploaded by this role (in my case, SSL certificates & keys).

For the next person - I offer this advice.  If you don't want to have to put your files in the middle of someone else's role, and have your files more closely located to where you are running the role from - like such:
