### ISSUE TITLE
Missing default vars in http/default.conf.j2

### ISSUE THREAD

**Issue by Metalrex100** [nginxinc/ansible-role-nginx#179]
If you creating web_server for php, you might not need variables like:
`http_demo_conf`

and in location section:
`html_file_location`
`html_file_name`
`autoindex`

In `http/default.conf.j2` file there are no default values for these vars.
Is there any reason for missing defaults?
If not, I can suggest PR with default values for these vars.

**Comment by alessfg** [comment]
You are right that you may not need those variables. However, if you don't need them you can comment out/delete the parameter on your playbook and they will not be used. (And some of them such as `autoindex` do have a default value, unless you mean something different). That being said, feel free to submit a PR if you have any improvements in mind 😄
