### ISSUE TITLE
Consider including /etc/nginx/sites-enabled/* in templates/nginx.conf.j2 

### ISSUE THREAD

**Issue by jwatt** [nginxinc/ansible-role-nginx#180]
I'm not sure where the convention of putting config files in `/etc/nginx/sites-available/` and symlinking to `/etc/nginx/sites-enabled/` originates from, or who all uses it, but it seems to be very common in Nginx tutorials out there. On the Ubuntu system I'm playing with, the default `/etc/nginx/nginx.conf` includes the lines:

```
        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*;
```

But it seems that `ansible-role-nginx/templates/nginx.conf.j2` only includes the former line. It would make this role more user friendly if `nginx.conf.j2` would include the latter too.

**Comment by alessfg** [comment]
`/etc/nginx/sites-available/` originates from Apache configuration files (as does virtual hosts, another common term you'll find in many NGINX tutorials). Alas, this is not a practice that necessarily follows NGINX best practices. 

What could be, perhaps, implemented, is the option to let users specify multiple locations using the `include` directive.
