### ISSUE TITLE
nginx_status_enable doesn't work

### ISSUE THREAD

**Issue by rgarrigue** [nginxinc/ansible-role-nginx#181]
Hi

The role's working fine for my couple of website, except the `nginx_status_enable: true` : you're writing the `stub_status.conf` in `/etc/nginx/conf.d/http/` which isn't included anywhere.

Best regards,

**Comment by alessfg** [comment]
Seems like stub status destination didn't get properly updated after a previous refactor. Merged a PR that should hopefully address any future issues like this by letting users specify the target destination of the stub status file.
