### ISSUE TITLE
events_custom_options is missing from defaults/templates.yml

### ISSUE THREAD

**Issue by IyadKandalaft** [nginxinc/ansible-role-nginx#207]
The [defaults/main/templates.yml](https://github.com/nginxinc/ansible-role-nginx/blob/master/defaults/main/template.yml) is missing the events_custom_options declaration despite the fact that it is supported in the [templates/nginx.conf.j2 template](https://github.com/nginxinc/ansible-role-nginx/blob/master/templates/nginx.conf.j2)

Existing template code references events_custom_options
`events {
    worker_connections  {{ nginx_main_template.worker_connections }};
{% if nginx_main_template.events_custom_options is defined and nginx_main_template.events_custom_options | length %}
{% for inline_option in nginx_main_template.events_custom_options %}
    {{ inline_option }};
{% endfor %}
{% endif %}
}`

The defaults/main/tempalte.yml should mention it even if it's commented out by default.  This avoids having users of this role reading the jinja template to determine if it's possible to inject custom events options.

**Comment by IyadKandalaft** [comment]
#208

**Comment by alessfg** [comment]
Solved by #208
