### ISSUE TITLE
HTTP configuration creation stopped working

### ISSUE THREAD

**Issue by thorian93** [nginxinc/ansible-role-nginx#209]
**Describe the bug**
After pulling the latest updates from the git repo, the role does not create proper http configuration files using the `nginx_http_template` variable.

**To reproduce**
1. Deploy NGINX role using playbook.yml
2. Find empty configuration files as described above. Only the `{{ anible_managed }}` line is there.

**Expected behavior**
The configuration files should be created following the values in the `nginx_http_template` variable.

**Your environment:**
 - Version of the NGINX Role or specific commit: b5baf3a2ae570d886a6acb6f6d6b9d5eea130e0f
 - Version of Ansible: 2.9.1
 - Target deployment platform: Ubuntu 18.04.03 LTS

**Additional context**
It worked perfectly before, although I can not specify the exact commit or version of the role.

**Comment by alessfg** [comment]
Hi @thorian93!

Can you share the playbook you are using? That'll help me debug the issue you're encountering.

Thanks,
Alessandro.

**Comment by thorian93** [comment]
Hi @alessfg!
I don't have hands on it now but it comes down to this:

```
hosts: all
become: yes
roles:
  - ansible-role-nginx
```

I have the `nginx_http_template` variable filled with two configs, one for HTTP and one for HTTPS. So i would expect to at least have the configuration files populated with some values.

The file detection works anyways, so the role sees the existing files and updates them with new files, which are empty apart from the `{{ ansible_managed }}` variable.

**Comment by alessfg** [comment]
Tests for templating seems to be fine if you look at https://travis-ci.org/nginxinc/ansible-role-nginx/jobs/624799967#L1241. There's been quite a few templating changes between the last two releases (0.12 and 0.13) so my best guess is that one of those changes broke your playbook? You can check https://github.com/nginxinc/ansible-role-nginx/blob/master/molecule/common/playbook_template.yml for an example playbook.

**Comment by thorian93** [comment]
Hm, alright, I will need to test that and don't know when I will be able to do so thoroughly.

Thanks for your support! :)

If no one else has this issue it is probably my configuration and not the role itself.

**Comment by vladp** [comment]
after updating the to the latest, my http config files became empty.
Depending when you created your ansible files, @thorian93 , you will have to restructure them to work with the new role.

I updated this role and my ansible files, about October 20 2019 or so, since then it seems critical structures have changed.

Specifically, now, the "servers" dictionary was introduced, and all the http servers now need to be underneath that.
I had to follow the https://github.com/nginxinc/ansible-role-nginx/blob/master/defaults/main/template.yml
to figure out the updated structure.

The streams config structure did not change.

**Comment by alessfg** [comment]
Yeah that's one of the main configuration changes that happened between 0.12 and 0.13 (and only a couple months ago too). You can find a complete list of the changes in the release notes https://github.com/nginxinc/ansible-role-nginx/releases/tag/0.13.0.

**Comment by thorian93** [comment]
Alright, I managed to get a minimum working example although it needs further adaption and testing. I think in a case of such complex variable structure some help would be nice for users on how to configure and maybe how to migrate if the structure changes again.

**Comment by alessfg** [comment]
I totally agree. There's some examples on the README and a more complete example at https://github.com/nginxinc/ansible-role-nginx/blob/master/molecule/common/playbook_template.yml but there's no question that documentation could be much better in this regard. 

I anticipate there's still going to be some templating structural changes in the next few releases (and before release 1.0) but I'll make a note to include notes on how to migrate template structure if it's necessary. In the meantime, PRs to improve documentation are always welcome!

**Comment by alessfg** [comment]
Quick update, I've started adding a Breaking Changes section to the Changelog (which will in turn be the base for any new release notes). This section should cover any instructions on how to migrate any playbooks if necessary.
