### ISSUE TITLE
apt update (after installation from the nginx repo) gives an error

### ISSUE THREAD

**Issue by erbap** [nginxinc/ansible-role-nginx#210]
ERROR:
N: Skipping acquire of configured file 'nginx/binary-i386/Packages' as repository 'https://nginx.org/packages/mainline/ubuntu bionic InRelease' doesn't support architecture 'i386'

SOLVED:
in nginxinc.nginx/tasks/opensource/setup-debian.yml I added [arch=amd64] to the default_repository since I don't think it someone is gone try to use this installation  method on an i386 based OS.

**Comment by alessfg** [comment]
Hi @erbap!

Do you think you could submit a PR?

Thanks!

**Comment by alessfg** [comment]
Fixed by #212
