### ISSUE TITLE
No package matching 'unit-nginx-plus-module-opentracing' found available, installed or updated

### ISSUE THREAD

**Issue by arslan70** [nginxinc/ansible-role-nginx#214]
Trying to use opentracing module
https://docs.nginx.com/nginx/admin-guide/dynamic-modules/opentracing/

1. Deploy NGINX role using playbook.yml
With below configuration
    vars:
    nginx_unit_enable: true
    nginx_unit_modules:
      - unit-nginx-plus-module-opentracing

Error: 
 failed: [instance] (item=unit-nginx-plus-module-opentracing) => {"changed": false, "item": "unit-nginx-plus-module-opentracing", "msg": "No package matching 'unit-nginx-plus-module-opentracing' found available, installed or updated", "rc": 126, "results": ["No package matching 'unit-nginx-plus-module-opentracing' found available, installed or updated"]}

**Expected behavior**
opentracing module should be installed

**environment:**
 - nginx_version: -r19

**Comment by alessfg** [comment]
Sadly, I don't think there's an opentracing module for NGINX Unit @arslan70.

**Comment by arslan70** [comment]
> Sadly, I don't think there's an opentracing module for NGINX Unit @arslan70.

thank you for the quick reply.
