### ISSUE TITLE
Missing endif in http/default.conf.j2 ?

### ISSUE THREAD

**Issue by mazz-seven** [nginxinc/ansible-role-nginx#222]
**Describe the bug**
Did you miss endif here? 
https://github.com/nginxinc/ansible-role-nginx/blob/0b176f847a7b43934434088d4f18feed7b156db9/templates/http/default.conf.j2#L89

I'm getting parse error

**Comment by alessfg** [comment]
It looks to me as if all if statements have the appropriate endif statement (plus, I'm pretty sure molecule would catch any missing endif statements).

Can you paste your parse error? Are you using the latest version of the role? Any extra info you can provide will help debug your issue 😄

**Comment by mazz-seven** [comment]
Sorry, my mistake  😄
