### ISSUE TITLE
Don't log status probing

### ISSUE THREAD

**Issue by rgarrigue** [nginxinc/ansible-role-nginx#225]
Hi

I ususally prefer to avoid logging this

> 127.0.0.1 - - [18/Feb/2020:05:57:35 +0000] "GET /nginx_status HTTP/1.1" 200 109 "-" "Go-http-client/1.1" "-"

Mind adding `access_log off;` around https://github.com/nginxinc/ansible-role-nginx/blob/master/tasks/conf/setup-status.yml#L9 ?

Best regards,

**Comment by alessfg** [comment]
Good suggestion @rgarrigue! I'll add it to the backlog.
