### ISSUE TITLE
Don't automatically add ssl to listen directives

### ISSUE THREAD

**Issue by meersjo** [nginxinc/ansible-role-nginx#235]
Currently, when an ssl: section is defined, the template automatically adds the ssl stanza to each configured listening port. This is a problem, as Nginx perfectly supports both http and https listeners in the same configuration - and that is a valuable feature, as it avoids duplication of configuration.

I propose to not add the ssl stanza automatically, but defer to the ssl setting for each individual listener port.

As a backwards-compatible change, the template could be changed to default to ssl when that section is present, but defer to the ssl setting in each individual listener declaration (ssl: false) if present - personally, however, I feel like that is counterintuitive, as it suddenly requires ssl to be explicitly disabled on existing ports when an ssl port is added.

**Comment by alessfg** [comment]
Hi @meersjo! You are absolutely right, adding the `ssl` parameter can lead to undesired behaviors. I don't think introducing a backwards compatible change would make much sense as you have already detailed -- it makes much more sense to add an option to manually set `ssl` per listener.

**Comment by meersjo** [comment]
Well, _technically_ it's already possible - you just add "ssl" to the port number :-p Would be good to have it formalised, though.

**Comment by xTrekStorex** [comment]
You could also add it to opts like you'd do with "http2"
(https://github.com/nginxinc/ansible-role-nginx/blob/master/templates/http/default.conf.j2#L83)

**Comment by alessfg** [comment]
After double checking this should be already possible as of 0.14.0 and #215. Feel free to reopen the issue if something's still not working as expected!
