### ISSUE TITLE
[enhancement request] Fall back to nginx -s reload when service is not available

### ISSUE THREAD

**Issue by BillHoo** [nginxinc/ansible-role-nginx#238]
**Is your feature request related to a problem? Please describe.**
Based on this issue: https://github.com/ansible/ansible-modules-core/issues/952
This role uses ansible service `state: reloaded` to reload nginx, but it is not reloaded at all in Ubuntu 16.04.1 TLS, when my `nginx.conf` have any errors, your handler still exit with no error.

**Describe the solution you'd like**
Fall back to `nginx -s reload` when service is not available like this situation.
No matter what solutions you'd like to use, please MAKE SURE nginx is reloaded, thus consumers like us could feel more safe and comfortable.

Thank you very much for provide this official role, hope it could soon become 1.x.x

**Comment by alessfg** [comment]
Thanks for reporting this @BillHoo! I had no idea this was a potential issue! I'll try to get on this as soon as I can.

**Comment by BillHoo** [comment]
@alessfg Thank you for timely reply, this is really important for us to use the official role in our production environment, will wait on your update. regards.

**Comment by alessfg** [comment]
Heya again, couple thoughts/questions:
1. Which distro are you deploying your playbook in? I'm assuming from your error description that your distro does not have a service system enabled, is that right?
2. Can you include a copy of your playbook (please edit out any sensitive data)?3. Can you try setting `nginx_debug_output` to true and see if NGINX fails as expected?

**Comment by BillHoo** [comment]
Hi, there's my answers

1. `Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-170-generic x86_64)`
2. The playbook is pretty simple

```ymal
---
- name: "Install Nginx"
  import_role:
    name: nginxinc.nginx
  vars:
    nginx_branch: stable
    nginx_cleanup_config: true
    nginx_cleanup_config_path:
      - "/etc/nginx/nginx.conf"
      - "/etc/nginx/conf.d"

- name: "Copy the nginx.conf which HAVE SYNTAX ERRORS"
  copy: src=nginx/nginx.conf dest=/etc/nginx/nginx.conf

# If i'm not forcing the reload, there will be no errors, but it should be.
# when use "nginx -s reload", the syntax error is prompted.
#- name: "Force a reload"
#  command: nginx -s reload
```

3. I'll try it latter, too busy today

**Comment by BillHoo** [comment]
Hi @alessfg , confirmed that when `nginx_debug_output` is enabled, the error is shown, but without it, the whole Role succeed with no error at all.

```json
FAILED! => {
  "changed": false,
  "cmd": ["nginx", "-T"],
  "msg": "non-zero return code",
  "rc": 1,
  "stderr": "nginx: [emerg] unexpected end of file, expecting \"}\" in /etc/nginx/nginx.conf:33\nnginx: configuration file /etc/nginx/nginx.conf test failed",
  "stderr_lines": ["nginx: [emerg] unexpected end of file, expecting \"}\" in /etc/nginx/nginx.conf:33", "nginx: configuration file /etc/nginx/nginx.conf test failed"],
  "stdout": "", "stdout_lines": []}
```

**Comment by alessfg** [comment]
Good to see! In that case I would recommend using that setting for now until I implement a start/reload path for cases where there might not be a service manager installed on the target system.

**Comment by BillHoo** [comment]
Got it, thank you!

**Comment by magicalyak** [comment]
Do we want this to be default or just have a variable enable the checking?

**Comment by alessfg** [comment]
Ideally we'd dynamically check if the system has some sort of service manager and then adjust how NGINX is handled on the fly.

**Comment by magicalyak** [comment]
Ok going to add a PR shortly.  @BillHoo if you want to test you could run the following and call ansible-role-nginx and run through your examples
ansible-galaxy install git+https://github.com/magicalyak/ansible-role-nginx.git,issue238

**Comment by magicalyak** [comment]
The above PR fixes the issue I replicated and the one I "think" @BillHoo had where a bad nginx.conf wouldn't trigger an error.  This is now resolved in that PR.

**Comment by BillHoo** [comment]
Thank you all, I'll have a test later this week and close the issue once verified.

**Comment by magicalyak** [comment]
@BillHoo any updates?

**Comment by BillHoo** [comment]
@magicalyak Sorry for the delay, I was also received your update to Ansible Galaxy days ago, but i'm in vacation, will feedback in tomorrow. thank you.

**Comment by BillHoo** [comment]
@magicalyak @alessfg 
Hi there, confirmed the Ansible Role nginx.nginx 0.14.0 fixed the issue.

```
16:28:01  RUNNING HANDLER [nginxinc.nginx : (Handler: All OSs) Reload NGINX] *************
16:28:02  fatal: [172.31.11.230]: FAILED! => {"changed": false, "cmd": ["nginx", "-s", "reload"]
```

I'm closing the ticket, thanks for all your help!

**Comment by BillHoo** [comment]
@magicalyak @alessfg 

Hi there, confirmed that `nginxinc.nginx 0.14.0` fixed the issue.

```
16:28:01  RUNNING HANDLER [nginxinc.nginx : (Handler: All OSs) Reload NGINX] *************
16:28:02  fatal: [x.x.x.x]: FAILED! => {"changed": false, "cmd": ["nginx", "-s", "reload"]
```

I'm closing the ticket. Thanks for all your effort on this!
