### ISSUE TITLE
Add the ability to specifiy PID emplacement

### ISSUE THREAD

**Issue by yodatak** [nginxinc/ansible-role-nginx#243]
Hi in Fedora 32 Server the Pid file and the systemd service file refer to  /run/nginx.pid 
Process: 1428955 ExecStartPre=/usr/bin/rm -f /run/nginx.pid (code=exited, status=0/SUCCESS)
insted of 
pid        /var/run/nginx.pid;

It could be interesting to support the PID parameter to permit more flexibility here:
https://github.com/nginxinc/ansible-role-nginx/blob/5a7731735ba6bd845a0ccf7350354142fdff602a/templates/nginx.conf.j2#L48

**Comment by alessfg** [comment]
Hi @yodatak! You'll be glad to know that this is already on the roadmap and I plan to include it in the next "major" update to the role (I don't have an ETA for it just yet) -- in the meantime if you want to get this implemented sooner feel free to create a PR 😉

**Comment by rgarrigue** [comment]
A though on the matter, /run/service.pid should be the default. Debian (Buster at least) also complain on any usage of /var/run. Here's a bit of info why : https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch05s13.html

**Comment by alessfg** [comment]
Ah good to know. I missed that memo 😄
