### ISSUE TITLE
Change in APT repo breaks 'apt update' for nginx packages on existing deployments

### ISSUE THREAD

**Issue by xTrekStorex** [nginxinc/ansible-role-nginx#245]
With commit https://github.com/nginxinc/ansible-role-nginx/commit/50a6338a356a74929dd861cf604f7a99470cc940 the arch qualification was added to the repository strings.
However the apt_repository Ansible module doesn't ensure an absolute state but only that the repo line exists.
This results in duplicate declarations on existing deployments like so:
```
> cat /etc/apt/sources.list.d/nginx_org_packages_mainline_debian.list

deb https://nginx.org/packages/mainline/debian/ buster nginx
deb-src https://nginx.org/packages/mainline/debian/ buster nginx
deb [arch=amd64] https://nginx.org/packages/mainline/debian/ buster nginx
deb-src [arch=amd64] https://nginx.org/packages/mainline/debian/ buster nginx

> apt update

[...]
W: Target Sources (nginx/source/Sources) is configured multiple times in /etc/apt/sources.list.d/nginx_org_packages_mainline_debian.list:2 and /etc/apt/sources.list.d/nginx_org_packages_mainline_debian.list:4
W: Target Packages (nginx/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/nginx_org_packages_mainline_debian.list:1 and /etc/apt/sources.list.d/nginx_org_packages_mainline_debian.list:3
W: Target Packages (nginx/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/nginx_org_packages_mainline_debian.list:1 and /etc/apt/sources.list.d/nginx_org_packages_mainline_debian.list:3
W: Target Translations (nginx/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list.d/nginx_org_packages_mainline_debian.list:1 and /etc/apt/sources.list.d/nginx_org_packages_mainline_debian.list:3
W: Target Translations (nginx/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/nginx_org_packages_mainline_debian.list:1 and /etc/apt/sources.list.d/nginx_org_packages_mainline_debian.list:3
W: Target Sources (nginx/source/Sources) is configured multiple times in /etc/apt/sources.list.d/nginx_org_packages_mainline_debian.list:2 and /etc/apt/sources.list.d/nginx_org_packages_mainline_debian.list:4
W: Target Packages (nginx/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/nginx_org_packages_mainline_debian.list:1 and /etc/apt/sources.list.d/nginx_org_packages_mainline_debian.list:3
W: Target Packages (nginx/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/nginx_org_packages_mainline_debian.list:1 and /etc/apt/sources.list.d/nginx_org_packages_mainline_debian.list:3
W: Target Translations (nginx/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list.d/nginx_org_packages_mainline_debian.list:1 and /etc/apt/sources.list.d/nginx_org_packages_mainline_debian.list:3
W: Target Translations (nginx/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/nginx_org_packages_mainline_debian.list:1 and /etc/apt/sources.list.d/nginx_org_packages_mainline_debian.list:3
```

To fix that I now need to purge said file on all hosts with another temporary task...
For this reason I personally use the template module to ensure the state of sources.list files, instead of apt_repository. IMHO this role should do the same since it creates its own list file and should have absolute control over its state.

Furthermore arch-qualifying deb-src lines doesn't make any sense. See https://wiki.debian.org/Multiarch/HOWTO#Configuring_architectures

**Comment by alessfg** [comment]
Hm interesting. I made that change due to https://github.com/nginxinc/ansible-role-nginx/issues/210, but if there's a better way to address that issue I'm all for it. You do make a good point re using the `template` module instead of `apt_repository`. It'd be worth exploring for sure. And yup you're right, arch qualifying deb-src lines makes no sense. Sorry about that! I'll get rid of it asap 😄

**Comment by alessfg** [comment]
Hey @xTrekStorex! 

Finally getting around removing the arch qualifier from the source repo list. Re your first comment re using the `template` vs the `apt_repository` module, I'll have to think about it. You ran into an unfortunate side effect/error of using `apt_repository` but I don't foresee any further changes to the repo lists in the near future.

Cheers.

**Comment by xTrekStorex** [comment]
Hi @alessfg,

it's nice this gets cleaned up, but this will duplicate the deb-src line again since it's still done via apt_repository. 
So that's a repo change in itself already. :P And from experience with plenty FOSS upstream repos I wouldn't be so sure the repo URL won't change again - even if just by a single character. Guess I'll have to whip up another temp playbook to fix the duplicate lines on all hosts again then..

**Comment by alessfg** [comment]
🤦 me. Sorry about that! There's plans to add a variable soonish (hopefully by end of week) to choose whether you want to install `nginx` or configure `nginx`. Once that variable gets implemented you can perhaps simply set the role to not install `nginx` and thus the repo list won't error out? I'll document the breaking change (yet again) once the Changelog gets updated. (I'll rethink the template option or other alternatives if the repo source changes again in the near future.)
