### ISSUE TITLE
selinux handling

### ISSUE THREAD

**Issue by magicalyak** [nginxinc/ansible-role-nginx#247]
**Is your feature request related to a problem? Please describe.**
When I want to enforce selinux or forget to turn it off, I will get strange errors and seem to troubleshoot the issue for too long

**Describe the solution you'd like**
I would like for the role to handle selinux ports for me so that enforcing can be used.

**Describe alternatives you've considered**
selinux permissive but this feels weak....

**Additional context**
Just thought I found a bug but it was selinux...

**Comment by alessfg** [comment]
Implemented by #272.
