### ISSUE TITLE
Support for Ubuntu 20.04 LTS (Focal Fossa)

### ISSUE THREAD

**Issue by sergiuszkierat** [nginxinc/ansible-role-nginx#248]
**Is your feature request related to a problem? Please describe.**
A task [setup-debian.yml](https://github.com/nginxinc/ansible-role-nginx/blob/master/tasks/amplify/setup-debian.yml) fails with the following exception

```
The full traceback is:
  File "/tmp/ansible_apt_repository_payload_4hefh4mw/ansible_apt_repository_payload.zip/ansible/modules/packaging/os/apt_repository.py", line 548, in main
  File "/usr/lib/python3/dist-packages/apt/cache.py", line 591, in update
    raise FetchFailedException(e)
fatal: [host]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "codename": null,
            "filename": "nginx-amplify",
            "install_python_apt": true,
            "mode": null,
            "repo": "deb [arch=amd64] http://packages.amplify.nginx.com/ubuntu/ focal amplify-agent",
            "state": "present",
            "update_cache": true,
            "validate_certs": true
        }
    },
    "msg": "apt cache update failed"
}
```

**Describe the solution you'd like**
Add packages for [_focal_](https://releases.ubuntu.com/20.04/) within http://packages.amplify.nginx.com/ubuntu/dists/

**Describe alternatives you've considered**
n/a

**Additional context**
There is a related issue https://github.com/nginxinc/nginx-amplify-agent/issues/177

**Comment by alessfg** [comment]
This is real useful information @sergiuszkierat! I'll make sure to add the relevant packages while I prepare the role to support `focal`!

**Comment by alessfg** [comment]
Quick update -- I have no ETA for when there'll be `focal` packages available for NGINX Amplify. In the meantime I can implement a workaround 😄

**Comment by telepath** [comment]
I've used the role to successfully install and configure nginx on focal. So, good job!

**Comment by sergiuszkierat** [comment]
> Quick update -- I have no ETA for when there'll be `focal` packages available for NGINX Amplify. In the meantime I can implement a workaround

Please update me, when the workaround come :dancers:

**Comment by alessfg** [comment]
@telepath -- NGINX core (OSS/Plus) does have `focal` packages readily available. It's NGINX Amplify that's the issue 😛 

And yes @sergiuszkierat will do! I'll link the PR to this issue 😄

**Comment by alessfg** [comment]
Quick update (and not with great news) -- made the decision to hold off on implementing the fix in the linked issue. This role aims to only support officially developed distributions and implementing a side fix would not fit the current goals of the role. `focal` support will have to come from the NGINX Amplify team.

**Comment by sergiuszkierat** [comment]
thanks for updating us, it seems reasonable

**Comment by defanator** [comment]
@sergiuszkierat @alessfg please check https://github.com/nginxinc/nginx-amplify-agent/issues/181#issuecomment-662107703

**Comment by alessfg** [comment]
Nice! I'll work on implementing that as soon as I can.

**Comment by alessfg** [comment]
I've implemented the Ubuntu focal experimental support in #292. Hopefully that works out for everyone! 😄

**Comment by TimeTravelersHackedMe** [comment]
Looks like there is still a kink to work out. I posted details on the PR #292

**Comment by alessfg** [comment]
^Solved

**Comment by sergiuszkierat** [comment]
Sorry for delayed feedback, I confirm that it is working. Good job @alessfg :+1:

**Comment by AlexanderMatveev** [comment]
@sergiuszkierat @alessfg Looks like not working on fresh 20.04:

> E: The repository 'https://packages.amplify.nginx.com/ubuntu focal Release' is not signed.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> 
>   8. Updating repository ... failed.
> 
>  Please check the list of the supported systems here https://git.io/vKkev

**Comment by alessfg** [comment]
Perchance it's a one off error? If it keeps happening there's sadly not much I can do until `focal` is added as an officially supported platform.

**Comment by defanator** [comment]
JFTR, latest agent version (1.8.0) now officially supports Ubuntu 20.04. Please follow the docs in order to upgrade:

https://amplify.nginx.com/docs/guide-installing-and-managing-nginx-amplify-agent.html#updating-the-agent
