### ISSUE TITLE
When on Fedora 31:  CentOS repository error

### ISSUE THREAD

**Issue by vladp** [nginxinc/ansible-role-nginx#253]
Fedora:

[root@lnx-16 etc]# cat /etc/fedora-release 
Fedora release 31 (Thirty One)

 
vagrant image:
Vagrant.configure("2") do |config|
  config.vm.box = "generic/fedora31"
end
version 3.0.2

I am getting error when running the role

`<10.0.1.109> (0, b'\r\nErrors during downloading metadata for repository \'nginx\':\r\n  - Status code: 404 for https://nginx.org/packages/mainline/centos/31/x86_64/repodata/repomd.xml (IP: 95.211.80.227)\r\nError: Failed to download metadata for repo \'nginx\': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried\r\nIgnoring repositories: nginx\r\n\r\n{"msg": "Nothing to do", "changed": false, "results": [], "rc": 0, "invocation": {"module_args": {"name": ["openssl"], "allow_downgrade": false, "autoremove": false, "bugfix": false, "disable_gpg_check": false, "disable_plugin": [], "disablerepo": [], "download_only": false, "enable_plugin": [], "enablerepo": [], "exclude": [], "installroot": "/", "install_repoquery": true, "install_weak_deps": true, "security": false, "skip_broken": false, "update_cache": false, "update_only": false, "validate_certs": true, "lock_timeout": 30, "conf_file": null, "disable_excludes": null, "download_dir": null, "list": null, "releasever": null, "state": null}}}\r\n', b'Shared connection to 10.0.1.109 closed.\r\n')
`

**Comment by vladp** [comment]
oh, sorry.
it seems like you no longer support Fedora (I am using it in my integration environment, so run into this error).
I guess, if Fedora will no longer be supported, makes sense to close the issue.

**Comment by alessfg** [comment]
Hey @vladp! While the role never officially supported Fedora, it has always supported RHEL/CentOS. Now, the issue is that NGINX does not produce packages for Fedora out of the box, so this role fails to find a suitable package for Fedora.

My suggestion would be to try to use the build from source parameters and see if that works. The task will take a bit longer to complete but that might be the best option available at the moment.

**Comment by vladp** [comment]
Ah, ok. thank you. 

After some thinking, I am taking a view to replace Fedora with CentOS 8 for our purposes..

I use multi-OS installations in integration environment, not just to anticipate client needs, but, also as sort of 'reconnaissance' to understand what potentially future changes will impact our system.
Fedora was a good proxy for redhat based distros for that. 
But now that CentOS8 is updating more often, we will just replace our Fedora with CentOS8.

I will keep your suggestion in mind though,  as I have to update our FreeBSD and OpenBSD ansibles.

thank you again !
