### ISSUE TITLE
Unable to download the nginx signing key due to ssl error on ubuntu Focal

### ISSUE THREAD

**Issue by alanmcg** [nginxinc/ansible-role-nginx#255]
**Describe the bug**
Unable to download the nginx signing key due to ssl error on ubuntu Focal docker image

> fatal: [default]: FAILED! => {"changed": false, "msg": "Failed to download key at https://nginx.org/keys/nginx_signing.key: Request failed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>"}

**To reproduce**
- hosts: host1
  roles:
    - { role: nginx }

**Expected behavior**
nginx should be installed

**Your environment:**
Deploying nginx on ubuntu docker with packer and ansible (packer calls the ansible provisioner)
ansible 2.9.6

It is possible to download the key separately with curl / wget no problem and no ssl errors are reported.

**Comment by alessfg** [comment]
Hm that is a weird error. Molecule tests on all previous versions of Ubuntu seem to be passing just fine, and I would not expect the `apt_key` module to behave any differently between systems. I'll get back to this once I formalize Ubuntu Focal support. Can you check that you have the relevant `ca-certificates` package installed on your Docker container in the meantime?

**Comment by alessfg** [comment]
I've added Ubuntu Focal tests and everything seems to be working as intended. The issue you are seeing is most likely related to your system.
