### ISSUE TITLE
NGINX fails to start on SELinux enabled systems, when I install from nginx_repository

### ISSUE THREAD

**Issue by cubit9** [nginxinc/ansible-role-nginx#261]
**Describe the bug**
This is not a new bug. The problem is already reported here:
```
# Nginx will fail to start if /run/nginx.pid already exists but has the wrong
# SELinux context. This might happen when running `nginx -t` from the cmdline.
# https://bugzilla.redhat.com/show_bug.cgi?id=1268621
```

**Your environment:**
 - Version of the NGINX Role or specific commit
master
 - Version of Ansible
ansible 2.9.6
 - Target deployment platform
CentOS 8

**Comment by cubit9** [comment]
I have found a workaround, who is working for me so far. Maybe not the right way. But here a short description.
I changed task for the installation of NGINX a little and upload a new `nginx.systemd` to the server to overwrite the `nginx.systemd` file, which comes with the installation.

My new `nginx.systemd` looks like this:

```
[Unit]
Description=nginx - high performance web server
Documentation=http://nginx.org/en/docs/
After=network-online.target remote-fs.target nss-lookup.target
Wants=network-online.target

[Service]
Type=forking
PIDFile=/var/run/nginx.pid
# Nginx will fail to start if /run/nginx.pid already exists but has the wrong
# SELinux context. This might happen when running `nginx -t` from the cmdline.
# https://bugzilla.redhat.com/show_bug.cgi?id=1268621
ExecStartPre=/usr/bin/rm -f /var/run/nginx.pid
ExecStartPre=/usr/sbin/nginx -t
ExecStart=/usr/sbin/nginx -c /etc/nginx/nginx.conf
# Fix for the error message:
# systemd[1]: nginx.service: Failed to parse PID from file /var/run/nginx.pid: Invalid argument
# https://stackoverflow.com/questions/42078674/nginx-service-failed-to-read-pid-from-file-run-nginx-pid-invalid-argument
# https://bugs.launchpad.net/ubuntu/+source/nginx/+bug/1581864
ExecStartPost=/bin/sleep 0.1
# Maybe a better workaround then directly overwrite /lib/systemd/system/nginx.service is described here
# https://superuser.com/questions/1267366/can-i-safely-edit-nginx-systemd-unit-file-lib-systemd-system-nginx-service-su
ExecReload=/bin/kill -s HUP $MAINPID
ExecStop=/bin/kill -s TERM $MAINPID
KillSignal=SIGQUIT
TimeoutStopSec=5
KillMode=mixed
PrivateTmp=true

[Install]
WantedBy=multi-user.target
```

**Comment by alessfg** [comment]
Hi @cubit9!

This seems to be an issue specific to NGINX, not this Ansible role per se. I would recommend getting in touch with the core development team via the NGINX mailing list (https://mailman.nginx.org/mailman/listinfo) and see what their thoughts are on this issue.

I'm closing this issue for now, but feel free to reopen/create a new issue if/when you hear back anything from the core team that's actionable on the Ansible role.

Cheers 😄
