### ISSUE TITLE
Host to install Nginx-extras?

### ISSUE THREAD

**Issue by dapi** [nginxinc/ansible-role-nginx#269]
**Is your feature request related to a problem? Please describe.**

Ia want to use `nginx-extras` instead of `nginx` package.

**Describe the solution you'd like**

Add variable to setup Nginx package name

**Comment by magicalyak** [comment]
In other words you want to change the name of the package you install into a variable you could modify?

**Comment by alessfg** [comment]
Hi @dapi! 

`nginx-extras` is a distro supported package that adds a lot of extra modules and integrations to `nginx` that we do not necessarily support. As such, I am not comfortable in providing support for it within this role. That being said, you can always set `nginx_enable` to `false` and install `nginx-extras` package in a `pre_task` if you so wish.

Cheers,
Alessandro.
