### ISSUE TITLE
Gentoo support

### ISSUE THREAD

**Issue by necrose99** [nginxinc/ansible-role-nginx#273]
https://github.com/gentoo-ansible/role-nginx 

not sure if this role i'd trust at 5 years stale ,  however looks to do most of the basic 
USE=""option a, b , c"  emerge www-server/nginx

as gentoo can toggle libraries on/off like Broti compression , 
email/webmail  use case hosting flags ... 

however merging into this role might be a consideration , 
and least better supported as well.

**Comment by alessfg** [comment]
Gentoo is not an officially supported NGINX distribution. I would recommend checking out the option to build NGINX from sources https://github.com/nginxinc/ansible-role-nginx/blob/master/defaults/main/main.yml#L32-L36 and see if that'll fit your use case.
