### ISSUE TITLE
Add IPv6 support for listen directives in stream template

### ISSUE THREAD

**Issue by schmitmd** [nginxinc/ansible-role-nginx#286]
**Is your feature request related to a problem? Please describe.**
TCP/UDP streams cannot be configured by the listen_address directive for IPv6.  The template only supports IPv4.

**Describe the solution you'd like**
The streams template should be able to add a listen directive for an IPv6 address via quoted YAML strings in Ansible variables.  Something like "listen_ipv6_address" would suffice.

**Describe alternatives you've considered**
The custom_options part can probably do this, but seems like the wrong place to be defining a basic listen directive.

**Additional context**
in templates/stream/default.conf.j2:
...
```jinja2
server {
{% if item.value.network_streams[stream].listen_address is defined and item.value.network_streams[stream].listen_port is defined %}
{% if item.value.network_streams[stream].listen_address == 'localhost' %}
{% if item.value.network_streams[stream].udp_enable %}
    listen {{ item.value.network_streams[stream].listen_port }} udp;
{% else %}
    listen {{ item.value.network_streams[stream].listen_port }};
{% endif %}
{% else %}
{% if item.value.network_streams[stream].udp_enable %}
    listen {{ item.value.network_streams[stream].listen_address }}:{{ item.value.network_streams[stream].listen_port }} udp;
{% else %}
    listen {{ item.value.network_streams[stream].listen_address }}:{{ item.value.network_streams[stream].listen_port }};
{% endif %}
{% endif %}
{% elif item.value.network_streams[stream].listen_port is defined %}
{% if item.value.network_streams[stream].udp_enable %}
    listen {{ item.value.network_streams[stream].listen_port }} udp;
{% else %}
    listen {{ item.value.network_streams[stream].listen_port }};
{% endif %}
{% endif %}
```
...

**Comment by alessfg** [comment]
I've "ported" over the listen structure used in `http` templates to `stream` templates. You should now be able to customize the `listen` directive as you see fit 😄
