### ISSUE TITLE
configuration example for php config

### ISSUE THREAD

**Issue by DO1JLR** [nginxinc/ansible-role-nginx#295]
Hello

Thank you very much for this Ansible role. I like to use it when I need a nginx server and some configuration.

Now I'm afraid I might have reached a limit. Now I want to create a website with PHP. But I can't find any hint in the molecule examples or in the templates themselves how and if that works.

Is one of the existing templates for this role designed to support PHP? Or does it result in writing an own template with PHP support (inspired by http/default.conf.j2 )?

Thanks and stay healthy

**Comment by alessfg** [comment]
There's no PHP specific config templates or examples at the moment but you can find an example using `custom_options` here https://github.com/nginxinc/ansible-role-nginx/blob/master/molecule/common/playbooks/template_converge.yml#L326-L335

**Comment by DO1JLR** [comment]
thanks.

I will give ``custom_options`` a try.
