### ISSUE TITLE
python-apt package is not available in Ubuntu 20.04.1 LTS

### ISSUE THREAD

**Issue by b0ric** [nginxinc/ansible-role-nginx#297]
**Describe the bug**
Installation of dependencies fails.

**To reproduce**
1. Try to deploy NGINX role on Ubuntu 20.04.1 LTS 
3. See error: `FAILED! => {"changed": false, "msg": "No package matching 'python-apt' is available"}`

**Expected behavior**
`python-apt` is not available on Ubuntu 20.04.1 LTS and be excluded from the dependencies. 

**Your environment:**
-   master branch from the repo
-   Version of Ansible: 2.9.11
-   Target deployment platform: Ubuntu 20.04.1 LTS

**Comment by alessfg** [comment]
I can't seem to replicate the issue on my end. My Ubuntu 20.04.01 LTS EC2 VM seems to include `python-apt`. Can you check which, if any, python-apt package is included in your VM?

**Comment by b0ric** [comment]
Hi @alessfg, just re-created the server with the same Ubuntu 20.04.01 LTS AMI from Canonical and it passed.
Looks like a false positive on my end.

**Comment by curtisspendlove** [comment]
I know this is closed, but just wanted to add.

I created a Digital Ocean Droplet with 20.04.01 this evening and got the same error.

I noticed it was saying in the MOTD (before I trashed that with extreme prejudice) that there was immediately an update available.

```
$ sudo apt update && sudo apt list --upgradable

Listing... Done
bcache-tools/focal-updates 1.0.8-3ubuntu0.1 amd64 [upgradable from: 1.0.8-3]
open-vm-tools/focal-updates 2:11.1.0-2~ubuntu20.04.1 amd64 [upgradable from: 2:11.0.5-4]
python3-distupgrade/focal-updates 1:20.04.24 all [upgradable from: 1:20.04.23]
python3-software-properties/focal-updates,focal-security 0.98.9.2 all [upgradable from: 0.98.9.1]
software-properties-common/focal-updates,focal-security 0.98.9.2 all [upgradable from: 0.98.9.1]
ubuntu-release-upgrader-core/focal-updates 1:20.04.24 all [upgradable from: 1:20.04.23]
```

A `sudo apt upgrade` fixed it. I'm guessing there might be a slight lag at the moment between certain images. :: shrug ::
