### ISSUE TITLE
Nginx Plus install w/ ansible role in Ubuntu

### ISSUE THREAD

**Issue by carldubois** [nginxinc/ansible-role-nginx#305]
Does this work for ubuntu 18.04? Trying to install plus:
  roles:
    - nginxinc.nginx
  vars:
     nginx_debug_output: true
     typeo plus
     license:
       certificate: /etc/ssl/nginx
       key: /etc/ssl/nginx

Skipped over Plus install.

**Comment by alessfg** [comment]
Seems as if you are missing the `nginx` suffix before your variable names. You should use `nginx_type` instead of `type` and `nginx_license` instead of `license`.
