### ISSUE TITLE
'Remove NGINX Configuration Files' step failing

### ISSUE THREAD

**Issue by Migsi** [nginxinc/ansible-role-nginx#310]
**Describe the bug**
The nginx role fails on "(Setup: All OSs) Remove NGINX Configuration Files" with the given error message:
`fatal: [playground.example.com]: FAILED! => {
    "msg": "Unexpected templating type error occurred on ({{ nginx_config_files.results | default('') | map(attribute='files') | sum(start=[]) | map(attribute='path') | list + nginx_cleanup_config_files | default('') }}): can only concatenate list (not \"str\") to list"
}`

**To reproduce**
1. Deploy NGINX role using playbook.yml (configured to setup a reverse proxy only; does not seem to be the root cause though)
2. Waiting for the "(Setup: All OSs) Remove NGINX Configuration Files" step to be executed
3. See error

**Expected behavior**
The role proceeds through this step as always and does not stall provisioning.

**Your environment:**
-   nginxinc.nginx (0.15.0)
-   ansible 2.9.6
-   ubuntu server 18.04.5 LTS

**Additional context**
I'm not sure if it helps, but the machine executing the playbook is running ubuntu 20.04 LTS. The role was working flawless until my recent (1 day ago) --force install of all galaxy obtained roles.

**EDIT**: I opened a new issue over at the nginx config repository, as I didn't notice the repo split earlier, please close this issue.

**EDIT2**: I'm getting unsure about where the issue actually should be placed. As I just updated the role via a forced download from galaxy, did I even get the new config role? Would my properties set for the nginx configuration have been ignored if didn't fail on this particular cleanup task?

**Comment by alessfg** [comment]
Closing in favor of https://github.com/nginxinc/ansible-role-nginx-config/issues/15
