### ISSUE TITLE
Unsupported parameters (rpm_key) 

### ISSUE THREAD

**Issue by rharink** [nginxinc/ansible-role-nginx#328]
**Describe the bug**
I get the following error on RHEL8:
```
TASK [nginxinc.nginx : (Amazon Linux/CentOS/Oracle Linux/RHEL/SLES) Add NGINX signing key] ***
Unsupported parameters for (rpm_key) module: fingerprint Supported parameters include: key, state, validate_certs
```

**To reproduce**
1. Deploy NGINX role on RHEL8
2. Fails see  error above

**Expected behavior**

**Your environment:**
-   Nginx 19
-   Ansible 2.8
-   RHEL8

**Additional context**
Always worked in a production pipeline, started failing today.

Could someone help me please, thanks!

**Comment by alessfg** [comment]
Ah it's because I introduced a new parameter in the latest release that only works starting in Ansible 2.9 (https://docs.ansible.com/ansible/latest/modules/rpm_key_module.html). Any chance you could upgrade to 2.9? The parameter adds a little extra security to the role.

**Comment by rharink** [comment]
Thanks! i'll upgrade to Ansible 2.9.
