### ISSUE TITLE
Nginx modules are not enabled upon installation - PLUS

### ISSUE THREAD

**Issue by fr6nco** [nginxinc/ansible-role-nginx#347]
**Describe the bug**
install-modules.yml only installs the module, but wont add the load_module directive into nginx.conf. This feature was working a few releases back.

**To reproduce**
install nginx plus (probably non plus has the issue too) and add module. e.g. njs.

**Expected behavior**
Module installed (which is OK). Load_module directive added to nginx.conf

**Your environment:**
```
 [root@s4-h12-cdn ~]# nginx -v
 nginx version: nginx/1.19.0 (nginx-plus-r22)
```

**Comment by alessfg** [comment]
Heya, this is working as intended. Any config related tasks (e.g. adding the `load_module` directive) are now handled by the [`nginx_config`](https://github.com/nginxinc/ansible-role-nginx-config) role.

**Comment by fr6nco** [comment]
Ah great. Thanks for the update, I wasn't aware of this. I see the deprecation warning in the readme now.
