### ISSUE TITLE
configuring nginx to be state 'running'

### ISSUE THREAD

**Issue by IRobL** [nginxinc/ansible-role-nginx#36]
I've gone up and down the configurations and roles, and I don't see a way of enforcing that the service actually be running.  Is there a way to configure this without writing a custom `systemd` task to enforce that the service be switched on if it's ever switched off?

**Comment by alessfg** [comment]
Hi @IRobL!

In Ansible, handlers are responsible for ensuring that NGINX will be running once the role is deployed (you can find these role's handlers [here](https://github.com/nginxinc/ansible-role-nginx/blob/master/handlers/main.yml)). However, Ansible uses a push model - this means that there's no simple way to ensure that NGINX is restarted if it's ever switched off. There are a couple alternatives however:
1) Use a custom `systemd` task
2) Use a custom cron/daemon script that checks NGINX's status and restarts NGINX/reruns the Ansible role
3) Use Ansible Tower - this allows you to run scheduled jobs

**Comment by IRobL** [comment]
Ty for the prompt clarification!
