### ISSUE TITLE
error on signing key

### ISSUE THREAD

**Issue by ojan** [nginxinc/ansible-role-nginx#4]
Hello,

Trying to install Nginx open source on Ubuntu 16.04 with Ansible 2.4.3 gives me the following error : 

>     TASK [nginxinc.nginx : (Install: APT OSs) Add APT NGINX Signing Key] ***********
    fatal: [instance]: FAILED! => {"changed": false, "cmd": "/usr/bin/apt-key adv --keyserver ha.pool.sks-keyservers.net --recv 573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62", "msg": "Error fetching key 573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62 from keyserver: ha.pool.sks-keyservers.net", "rc": 1, "stderr": "gpg: requesting key 7BD9BF62 from hkp server ha.pool.sks-keyservers.net\ngpg: key 7BD9BF62: public key \"nginx signing key <signing-key@nginx.com>\" imported\ngpg: Total number processed: 1\ngpg:               imported: 1  (RSA: 1)\ngpg: no writable keyring found: eof\ngpg: error reading `[stdin]': general error\ngpg: import from `[stdin]' failed: general error\ngpg: Total number processed: 0\n", "stderr_lines": ["gpg: requesting key 7BD9BF62 from hkp server ha.pool.sks-keyservers.net", "gpg: key 7BD9BF62: public key \"nginx signing key <signing-key@nginx.com>\" imported", "gpg: Total number processed: 1", "gpg:               imported: 1  (RSA: 1)", "gpg: no writable keyring found: eof", "gpg: error reading `[stdin]': general error", "gpg: import from `[stdin]' failed: general error", "gpg: Total number processed: 0"], "stdout": "Executing: /tmp/tmp.s3rZxQblst/gpg.1.sh --keyserver\nha.pool.sks-keyservers.net\n--recv\n573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62\n", "stdout_lines": ["Executing: /tmp/tmp.s3rZxQblst/gpg.1.sh --keyserver", "ha.pool.sks-keyservers.net", "--recv", "573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62"]}

Thanks

**Comment by alessfg** [comment]
Hi @ojan!

I cannot seem to replicate the error on my end. Have you tried re-running the role? (There may have been some temporary issues with the key server.) 

If the issue persists, can you check whether you have `gpg` installed on your Ubuntu machine?

Kind Regards,
Alessandro.

**Comment by ojan** [comment]
Hi @alessfg,

Thanks for your response. And sorry for my mistake. I just forgot to start my playbook with `become: true`. Shame on me :-)
