### ISSUE TITLE
Add AlmaLinux as supported OS

### ISSUE THREAD

**Issue by TonyBostonTB** [nginxinc/ansible-role-nginx#428]
### Is your feature request related to a problem? Please describe
I have to manually add AlmaLinux to the supported OSes

### Describe the solution you'd like
Make RedHat Vars work with AlmaLinux as this is one of the future CentOS 8 replacements

### Describe alternatives you've considered
I can manually edit files to get it tow work

**Comment by alessfg** [comment]
NGINX does not officially support AlmaLinux as of today so I can't add it to the list of supported OSes (that's not to say that you cannot install it using the role as is, and things might always change in the future).
