### ISSUE TITLE
Linux installation variables file linux.yml doesn't exists in defaults/main

### ISSUE THREAD

**Issue by DevopsVlogger** [nginxinc/ansible-role-nginx#434]
### Linux installation variables file linux.yml doesn't exists in defaults/main
The Linux installation variables file linux.yml doesn't exists in defaults/main.

https://github.com/nginxinc/ansible-role-nginx/blob/main/defaults/main/linux.yml

### To reproduce
Include the same.

### Expected behavior
It should be present to guide the Role's behavior on Linux systems.

**Comment by DevopsVlogger** [comment]
<img width="1352" alt="Screenshot 2021-08-19 at 7 31 37 PM" src="https://user-images.githubusercontent.com/1673949/130082365-5e190392-b584-4913-90d8-19d08a24fbde.png">


<img width="1008" alt="Screenshot 2021-08-19 at 7 31 30 PM" src="https://user-images.githubusercontent.com/1673949/130082426-02434062-5005-49f0-b84e-f828de13044a.png">

**Comment by alessfg** [comment]
Good catch @DevopsVlogger! As it turns out, those variables where moved to [`/vars/main.yml`](https://github.com/nginxinc/ansible-role-nginx/blob/main/vars/main.yml) sometime ago. Looks like the README needs to be updated!
