### ISSUE TITLE
Dependency missing on debian - installation fails

### ISSUE THREAD

**Issue by sseide** [nginxinc/ansible-role-nginx#44]
One debian (tested with minimal debian stretch) this role must enshure the package "apt-transport-https" is installed. You are on the safe side if you require this on every debian and ubuntu version as older ones have not installed this. Without this package fetching files from your nginx_repository will fail.

**Comment by alessfg** [comment]
Hi there!

Creating a task to install pre-required packages is on the list -- as is creating a task to check that the role supports the target deployment distro. I'll leave this issue open until then. Have you found any other packages in addition to `apt-transport-https` and `dirmngr` that need to be preinstalled?

Thanks,
Alessandro.

**Comment by sseide** [comment]
not up to the state i tried and wrote tickets for...
