### ISSUE TITLE
Install stable version of Nginx

### ISSUE THREAD

**Issue by FuhuXia** [nginxinc/ansible-role-nginx#440]
### Is your feature request related to a problem? Please describe
I want to have better control on what version of Nginx to be installed, not always the Mainline version. For example, I want it to always be the current stable version.

### Describe the solution you'd like
Offer a variable to choose stable/development/mainline version

**Comment by alessfg** [comment]
Hey @FuhuXia!
 
You can use [`nginx_version`](https://github.com/nginxinc/ansible-role-nginx/blob/main/defaults/main/main.yml#L25) to specify a version. You can also use [`nginx_branch`](https://github.com/nginxinc/ansible-role-nginx/blob/main/defaults/main/main.yml#L79) to choose between `mainline` and `stable`.

Does that help?

**Comment by alessfg** [comment]
Haven't heard back so I'm closing this for the time being. Feel free to reopen if you are still running into this issue!
