### ISSUE TITLE
Revert from NGINX `mainline` to NGINX `stable`

### ISSUE THREAD

**Issue by FuhuXia** [nginxinc/ansible-role-nginx#441]
### Is your feature request related to a problem? Please describe
On a fresh Ubunutu instance, Nginx 1.21.3 is installed by the current playbook. But if the Ubuntu has Nginx 1.18.0 on it, 1.21.3 is not installed, it keeps the 1.18.0.

### Describe the solution you'd like
Give user option to always get latest Nginx version by replacing existing one.

**Comment by alessfg** [comment]
Hey there!

Can you try using [`nginx_state`](https://github.com/nginxinc/ansible-role-nginx/blob/main/defaults/main/main.yml#L35) and seeing if that helps solve your issue?

**Comment by alessfg** [comment]
Haven't heard back so I'm closing this for the time being. Feel free to reopen if you are still running into this issue!

**Comment by FuhuXia** [comment]
Using `mainline` in ...
```
nginx_branch: mainline
nginx_state: latest
```
... will overwrite a `stable` install, but not the other way around. Any logic behind it?

**Comment by alessfg** [comment]
Well, fundamentally, `mainline` is the latest release. I can look into how much work it'd require to allow both use cases, but you would be the first user that I hear tries to go back from `mainline` to `stable` on the same install.

**Comment by alessfg** [comment]
I've done some more digging and looks like the `apt_repository` module appends the stable repository info to the mainline repository info. This in turn means that installing NGINX even when setting up the `mainline` will fail. 

A workaround would be to check for preexisting repository info and deleting it before setting up the new repository, but that can cause some issues related to preexisting environments. A different workaround would be to uninstall NGINX as a pretask to this role, and then setting the version specifically using `nginx_version`.

Looks like `allow_downgrades` is being introduced in Ansible 2.12 https://github.com/ansible/ansible/pull/74852. Once it's live I'll update the task to allow updating the NGINX version without having to previously uninstall NGINX.

**Comment by alessfg** [comment]
Finally circling back to this. I've added the necessary parameters in #475 to allow downgrades. You should be able to switch between `mainline` and `stable` by specifying both the branch and version. You can check https://github.com/nginxinc/ansible-role-nginx/blob/main/molecule/downgrade/converge.yml for a concrete example on how to do it.
