### ISSUE TITLE
Missing requirements

### ISSUE THREAD

**Issue by laurent-indermuehle** [nginxinc/ansible-role-nginx#443]
The Readme lacks some requirements I encountered when trying this role on a clean minimal install of Rocky 8: 

- The role doesn't work if runs on another user than root. Either, tell the user to run the playbook as root, or add "become: true" to the line that include the role: 

```yaml
  - role: nginxinc.nginx_core.nginx
    become: true
```
But it should be your responsibility to add the user escalation to root on tasks level, no?

- The following packets are required:
  - python3-libsemanage.x86_64
  - python3-policycoreutils.noarch

**Comment by alessfg** [comment]
You are right that the role requires root permissions to run. I'll add a note to the README/tests (there's nothing that indicates as much at the moment). That being said, I don't think I agree with automatically adding user escalation to root level within the actual tasks unless it's implemented as a `vars_prompt`, but that might require some R&D before it's properly implemented.

**Comment by laurent-indermuehle** [comment]
Oh no, I meant to add "become: true" on tasks like yum, service, etc... Nothing fancier than that.

**Comment by alessfg** [comment]
I see -- let me think about that and get back to you then 😄

**Comment by laurent-indermuehle** [comment]
I know 2 solutions:

- Execute the whole playbook as root (ansible_user: root). It is faster both to write yaml and execute. But security team doesn't like it.
- Add a prepare.yml step in Molecule that create a linux user with sudoers configured to allow sudo to root. Then use this user as ansible_user in converge.yml and verify.yml. This way, you catch any task that need root privileges during tests.

**Comment by alessfg** [comment]
> Execute the whole playbook as root (ansible_user: root). It is faster both to write yaml and execute. But security team doesn't like it.

Indeed, this solution would be less than ideal for a wide range of reasons.

> Add a prepare.yml step in Molecule that create a linux user with sudoers configured to allow sudo to root. Then use this user as ansible_user in converge.yml and verify.yml. This way, you catch any task that need root privileges during tests.

I could do this, but even if I caught exactly what tasks require root privileges, what good would that do if I don't explicitly make those tasks run as root in the role tasks? And that comes back to the original quandary of whether we should run anything as root by default given the potential issues that might stem from that.

I'm still not clear on what the best path forward, but for the time being I've at least added a small disclaimer in https://github.com/nginxinc/ansible-role-nginx/commit/f2b87855082dbb97b729085f9ad94bf4a6e0fd6d

**Comment by laurent-indermuehle** [comment]
Matrix is a great place to ask for advice on the multitude of Ansible channels. Especially this week. There is both the [Ansible Contributor Summit](https://www.eventbrite.com/e/ansible-contributor-summit-202109-tickets-167664955395) and [Ansible Fest 2021](https://www.ansible.com/ansiblefest) right now.

Because I fail to see the problem with `become: true` on tasks. For me, it's the normal way of using Ansible. But I may have missed something you're saying.

In the meantime, thanks for the message you added in [f2b8785](https://github.com/nginxinc/ansible-role-nginx/commit/f2b87855082dbb97b729085f9ad94bf4a6e0fd6d). It does the trick.

The only thing left is the required packages:

- python3-libsemanage.x86_64
- python3-policycoreutils.noarch

**Comment by alessfg** [comment]
What distro are you using? I test quite a few distributions by default and I have not run into those dependencies missing.

**Comment by laurent-indermuehle** [comment]
I tested on a clean minimal install of Rocky 8

**Comment by alessfg** [comment]
Oh, that is not a supported distribution for either NGINX OSS or NGINX Plus. Implementing a workflow to install those dependencies on that distribution would not currently be in the scope of this role. My best recommendation is to use `pre_task` to handle them.

**Comment by laurent-indermuehle** [comment]
oh right, I'm sorry.
Then I close my issue.
