### ISSUE TITLE
Adding nginx repository on debian is missing cache refresh

### ISSUE THREAD

**Issue by sseide** [nginxinc/ansible-role-nginx#45]
During your installation on Debian and Ubuntu you just add the new apt-key for your repository and registers the urls for them. Afterwards the package nginx will be installed. 

Because no "apt update" was performed (ansible module "apt" with attribute "update_cache=yes") prior installing the package the installation fails.

**Comment by alessfg** [comment]
Hi there!

Can you provide some more information on where exactly this happens and what you are trying to install (open source NGINX, NGINX Plus, NGINX Amplify, NGINX Unit)? 

In most cases the `apt-key.yml` task is followed by a `setup-debian.yml` task that executes the `apt_repository` module, which by default should update the `apt` cache.

**Comment by sseide** [comment]
Target: debian jessie
Host debian stretch with ansible 2.6.2

First tried to install opensource from os_repository which failed on geoip module (other ticket)
Than i switched to opensource from nginx_repository. there i got the error with missing "apt-transport-https". 
After installing transport manually rerun it - now error with signatures of the nginx provided packages. After running aptitude update manually the error vanished and i was able to install the package from your repo. Now i got back to the error with the geoip module...

Maybe my switch from os_repository to nginx_repository triggered it..

**Comment by alessfg** [comment]
I think that may have been what happened? I have Travis tests for Debian Jessie and open source NGINX installs without any issues.

**Comment by sseide** [comment]
Loooking back through my terminal output history it seems it is directly related to the missing apt-transport-https error.

The "apt-key" was added, the repository too and "apt-repository" doing the cache refresh it errored out with https support missing. Manually installing the transport triggered no refresh. And next ansible run did not reregister the repository - just skipped this step - therefor no cache refresh happened...

Close this as probably fixed with adding transport to your deps.
