### ISSUE TITLE
PCRE install from source fails because https://ftp.pcre.org is not available anymore

### ISSUE THREAD

**Issue by fernando-bosso** [nginxinc/ansible-role-nginx#467]
### Describe the bug

When downloading `pcre` dependency from source an error is thrown as shown below:

```
TASK [nginxinc.nginx_core.nginx : Download PCRE dependency] ******************************************************************
fatal: [172.31.9.40]: FAILED! => {"changed": false, "dest": "/tmp/pcre-8.44.tar.gz", "elapsed": 10, "msg": "Request failed: <urlopen error timed out>", "url": "https://ftp.pcre.org/pub/pcre/pcre-8.44.tar.gz"}
```

### To reproduce

1. Execute nginxinc.nginx_core collection

### Expected behavior

error `<urlopen error timed out>` should arise, because URL https://ftp.pcre.org is not available anymore, according to http://pcre.org/

### Your environment

- Version of the NGINX role or specific commit: **0.4.0**
- Version of Ansible **core 2.11.6**
- Version of Jinja2 (if you are using any templating capability) **2.10.1**
- Target deployment platform **RHEL**

**Comment by alessfg** [comment]
Nice catch! We don't test for source package install endpoints and this change slipped right past us!
