### ISSUE TITLE
Please state that this role is in alpha state in README

### ISSUE THREAD

**Issue by sseide** [nginxinc/ansible-role-nginx#47]
Please add the current state of the role at the head of your README file 
to let people know the development just started and it is not usable right now.

When it is finished and working the warning can be removed, but currently you can save a lot of people a lot of time with a short warning ahead...

**Comment by alessfg** [comment]
I wouldn't say the role is not usable -- it's been working pretty well for quite a few people! Nonetheless it is true that the role is still in active development, and the more people use it and report bugs/issues the better it will get!

That being said I have been tagging the releases as pre-releases but on hindsight that is definitely not enough. I'll add a comment to the README 😄

**Comment by sseide** [comment]
Thanks - seems i triggered the most unhappy path of all...  :-)
