### ISSUE TITLE
PCRE package address is not accessible anymore

### ISSUE THREAD

**Issue by mohsen-alizadeh** [nginxinc/ansible-role-nginx#490]
### Describe the bug

On installing Nginx from source code, it tries to install PCRE package from "https://ftp.exim.org/pub/pcre/{{ pcre_version }}.tar.gz",
This address is not available anymore

### To reproduce

Install nginx with source

**Comment by mohsen-alizadeh** [comment]
check out https://www.pcre.org/

```Note that the former ftp.pcre.org FTP site is no longer available. You will need to update any scripts that download PCRE source code to download via HTTPS, Git, or Subversion from the new home on GitHub instead.```

**Comment by alessfg** [comment]
You are right in that the original mirror is no longer supported. That being said, https://ftp.exim.org/pub/pcre does work, and role can download and install `pcre` from that mirror without any issues (I just double checked it on my end to be sure). Are you perhaps using an old version? If you are using `0.22` or later, this issue should be resolved.

**Comment by alessfg** [comment]
Closing this for the time being since the issue should have been solved in the latest release (`0.22`).
