### ISSUE TITLE
"(Handler) Print NGINX error if syntax check fails" always fails in check mode when nginx hasn't been installed yet

### ISSUE THREAD

**Issue by jwhite-ac** [nginxinc/ansible-role-nginx#495]
### Describe the bug

On a fresh Ubuntu 20.04 VM that does not yet have Nginx installed, the handler "(Handler) Print NGINX error if syntax check fails" is failing in check mode because it one of its conditions is `config_check.stderr_lines is defined` - `config_check` is set by the preceeding handler "(Handler) Check NGINX" which has `check_mode: false` set so that it always runs, which means that `config_check.stderr_lines` is always defined. Because the preceeding handler has `ignore_errors: true` set, the handler in question then fails becuase the return code is non-zero and `config_check.stderr_lines` is defined. 

### To reproduce

1. Deploy NGINX role using playbook.yml
```yaml
    - name: Install nginx
      import_role:
        name: nginxinc.nginx_core.nginx
```
2. Run against a fresh VM that does not have Nginx installed, in check mode
3. Error output:
```
RUNNING HANDLER [nginxinc.nginx_core.nginx : (Handler) Check NGINX] ************************************************************************************************************************************************************************************************************
fatal: [testvm]: FAILED! => {"changed": false, "cmd": ["nginx", "-t"], "delta": null, "end": null, "msg": "Unable to change directory before execution: [Errno 2] No such file or directory: b'/etc/nginx'", "rc": null, "start": null, "stderr": "", "stder
r_lines": [], "stdout": "", "stdout_lines": []}
...ignoring

RUNNING HANDLER [nginxinc.nginx_core.nginx : (Handler) Print NGINX error if syntax check fails] ********************************************************************************************************************************************************************************
fatal: [testvm]: FAILED! => {
    "config_check.stderr_lines": [],
    "failed_when_result": true
}
```

### Expected behavior

Handler is skipped as conditions should not be met in check mode when Nginx doesn't exist yet:
```
RUNNING HANDLER [nginxinc.nginx_core.nginx : (Handler) Check NGINX] ************************************************************************************************************************************************************************************************************
fatal: [testvm]: FAILED! => {"changed": false, "cmd": ["nginx", "-t"], "delta": null, "end": null, "msg": "Unable to change directory before execution: [Errno 2] No such file or directory: b'/etc/nginx'", "rc": null, "start": null, "stderr": "", "stder
r_lines": [], "stdout": "", "stdout_lines": []}
...ignoring

RUNNING HANDLER [nginxinc.nginx_core.nginx : (Handler) Print NGINX error if syntax check fails] ********************************************************************************************************************************************************************************
skipping: [testvm]
```

### Your environment

- nginx_core collection 0.5.0
- ansible-core 2.12.3
- target macine: ubuntu 20.04 
- ansible control: centos 7 (python 3.10.2 in a pyenv virtualenv)

### Additional context

Oddly, I did not have this problem in one of my own user account's pyenvs on Python 3.9.4 (on the ansible control node), however trying with fresh pyenvs in versions 3.9.2, 3.9.4, and 3.10.2 reproduce the error. I have not been able to determine why this particular pyenv skips the handler as expected.

Changing the when condition `config_check.stderr_lines is defined` to `config_check.stderr_lines != []` seems to fix the problem, however I haven't got a valid error state when installing Nginx to trigger it in a normal run to verify that this handler would still run.

**Comment by alessfg** [comment]
Nice catch! I'll try to reproduce it on my end as soon as I get a chance. I might end up removing the handler altogether now that anything config related has migrated to the NGINX config role.

**Comment by jwhite-ac** [comment]
Nice one. I think the preceeding handler would spit out its stderr lines on fail in any case so this handler may be redundant.
