### ISSUE TITLE
Absence of the handler for service enabling

### ISSUE THREAD

**Issue by AlekseiSidorenko** [nginxinc/ansible-role-nginx#54]
Hello Colleagues,

I didn't figure out the opportunity to enable nginx service by the role. I can't find it in handlers and tasks, so   in my case, I implemented the service enabling with post_tasks directive in my playbook.
Maybe I just miss something?

Is it OK if I will prepare a pull request with this opportunity?

**Comment by alessfg** [comment]
Hi @AlekseiSidorenko! There is no variable per se to start/enable the NGINX service, but there is a handler to start the NGINX service here https://github.com/nginxinc/ansible-role-nginx/blob/master/handlers/main.yml#L2-L5. Is this by any chance what you meant? If not feel free to submit a PR!

**Comment by AlekseiSidorenko** [comment]
Hi Alessandro!

I meant the adding nginx service to auto start.
In my case, I use your role during the baking AWS AMI. So when I'm starting the EC2 instance from this AMI, the nginx service is in stopped state.

Thank You!
I'll submit a PR with handler for service enabling.

**Comment by AlekseiSidorenko** [comment]
Hi @alessfg !
I've prepared short PR according to this discussion:
https://github.com/nginxinc/ansible-role-nginx/pull/55/files

**Comment by alessfg** [comment]
Merged!
