### ISSUE TITLE
Bug nginx_install_from: source (update zlib_version)

### ISSUE THREAD

**Issue by zadrix** [nginxinc/ansible-role-nginx#555]
### Describe the bug

Bug when I build with source ```nginx_install_from: source```

```
TASK [nginx : Download ZLib dependency] ****************************************
fatal: [web]: FAILED! => {"changed": false, "dest": "/tmp/zlib-1.2.12.tar.gz", "elapsed": 0, "msg": "Request failed", "response": "HTTP Error 404: Not Found", "status_code": 404, "url": "https://zlib.net/zlib-1.2.12.tar.gz"}
```

### To reproduce

Deploy NGINX role using playbook.yml with source ```nginx_install_from: source```

### Expected behavior

Build is not OK.
```zlib_version``` is defined in file ```vars/main.yml``` but **zlib-1.2.12** is no longer avaible
Good version is **zlib-1.2.13** since 13 october 2022

I think we need update ```zlib_version``` in ```vars/main.yml```

### Your environment

- nginx version: nginx/1.23.2
- main branch role
- ansible [core 2.13.5rc1]
- ubuntu2204 box vagrant

**Comment by alessfg** [comment]
This should be fixed as of 03ed41e4ec0d8f673eafb953c5a0a586d883529c! I also made a few changes to how building NGINX from source works, including a couple breaking changes (hopefully the last time I need to make breaking changes on this side of things). I don't have an ETA for when `0.23.3` will go live, but I am currently aiming for end of this month 😄
