### ISSUE TITLE
Is it possible to install nginx with streams without installing from source?

### ISSUE THREAD

**Issue by pvanagtmaal** [nginxinc/ansible-role-nginx#569]
Hi!

I'm in the process of installing NGINX through this role. We're relying on the stream module for load balancing and I see it's not in the `nginx_modules_list` (presumably because it's not a dynamic module).

I was wondering if this role is able to install the stream module without installing from source. If not I'll go for installing from source.

Thanks!

**Comment by alessfg** [comment]
You should be able to use streams with the default NGINX install! It's one of the modules that's compiled by default 😄 

See the section at the bottom of this doc re Dynamic Modules for more info https://nginx.org/en/linux_packages.html
