### ISSUE TITLE
variables names are not explicitly targeting nginx role

### ISSUE THREAD

**Issue by replicajune** [nginxinc/ansible-role-nginx#57]
Hi,

I was looking for a role to install nginx and came across yours.

I don't think it's currently usable in a production setup as variables names are too much generic. For example nothing tell me that `type`, `branch` or `module` would not overlap with another variable for another purpose.

I would like to propose a standardisation for all variables used by this role to begin with `nginx_`, making it clear that a variables set in a group var of a playbook will explicitly target a role that have something to do with nginx. :slightly_smiling_face:

For now, i'm using the role provided by geerlingguy, that have that kind of behavior, but I would love to use the official one once this problem is resolved.

Regards,

**Comment by alessfg** [comment]
Good suggestion @replicajune! I'll add it to the backlog 😄
