### ISSUE TITLE
When installing role on Amazon Linux Server I get an error

### ISSUE THREAD

**Issue by efreedom79** [nginxinc/ansible-role-nginx#58]
TASK [nginxinc.nginx : (Install: Debian/Ubuntu/CentOS/RedHat) Install NGINX] ***
fatal: [10.10.26.238]: FAILED! => {"changed": false, "msg": "Failure talking to yum: failure: repodata/repomd.xml from nginx: [Errno 256] No more mirrors to try.\nhttps://nginx.org/packages/mainline/centos/0/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found"}
        to retry, use: --limit @/home/ec2-user/GIT/vzw-messaging/ansible/aws/playbooks/ratings/buildRatings.retry

If I pass in  ansible_distribution_major_version=7 in the command line, it seems to work.
If I pass that variable in either the vars lines or in the role itself, it doesn't work.

**Comment by alessfg** [comment]
Correct me if I am mistaken, but it looks like you are trying to install the open source version of NGINX on Amazon Linux? If that's the case, open source NGINX does not support Amazon Linux. You may be able to get around it by installing the centos/rhel packages (as you found out), but we do not offer support for that distro.
