### ISSUE TITLE
Unable to download rpm signing key in corporate environment

### ISSUE THREAD

**Issue by hhenkel** [nginxinc/ansible-role-nginx#63]
Hi,
it is rather common in corporate environments, that servers are not able to connect to the internet. With the current playbook it is not possible to select a different location where one could fetch the rpm signing key.

If the issue is accepted I can provide a PR.

Kind regards,

Henning

**Comment by alessfg** [comment]
Hey @hhenkel that'd be a useful enhancement for the role! Feel free to submit a PR 😄

**Comment by alessfg** [comment]
Hi @hhenkel - the ability to select different locations for rpm/apt signing keys has been implemented in #84! Closing this issue for now.
