### ISSUE TITLE
Don't enable nginx repository if install_from: os_repository

### ISSUE THREAD

**Issue by aellert** [nginxinc/ansible-role-nginx#64]
If you choose install_from: os_repository, /etc/yum.repos.d/nginx.repo is still deployed.
So next time you do a 'yum update', the native nginx package is replaced by nginx offical RPM.

**Comment by alessfg** [comment]
Thanks for submitting the issue! I've done some testing on my end and there seems to be a few issues when using `install_from: os_repository`. However none of the issues I seem to find are related to your issue specifically. Could you share some more details like your target deployment distro and the playbook you are using to deploy the role?

**Comment by aellert** [comment]
Hi Alessandro,

I use Centos 7 and here is my playbook :

> ---
> - hosts: xxx
>   remote_user: yyy
>   become: yes
>   roles:
>     - nginxinc.nginx
>
>   vars:
>     install_from: os_repository
>
Result : The /etc/yum.repos.d/nginx.repo is created. Inside this file there
is a line "enabled=1".
Expected result : The /etc/yum.repos.d/nginx.repo is not created, removed
if present OR "enabled=0" is this file.

Thank you for your help.

**Comment by alessfg** [comment]
Thanks for the info! One more question - did you install the EPEL repository before running the role?

**Comment by aellert** [comment]
Yes epel-release-7-11.noarch was installed before running the playbook.

**Comment by alessfg** [comment]
Hey again @aellert! I've tested the setup you described and I cannot seem to replicate it. If I choose install from `os_repository` then `nginx.repo` does not get created. Did you perhaps run the role first without choosing `os_repository` and then changed the value of `nginx_install_from`?

**Comment by alessfg** [comment]
Closing this as there's not been any updates in over a year.
