### ISSUE TITLE
its not possible to define `nginx_version` with `nginx_install_from: source` to pin the version

### ISSUE THREAD

**Issue by olwe0002** [nginxinc/ansible-role-nginx#645]
### Is your feature request related to a problem? Please describe

[Here](https://github.com/nginxinc/ansible-role-nginx/blob/2d0843a22a5c580d29d25e1844aea453e2c8c117/tasks/opensource/install-source.yml#L328) the version gets set to the latest one in the specified branch. Its not possible to set it on your own and pin the version.

### Describe the solution you'd like

It should be possible to define `nginx_version` by your own. An easy way to achieve this would be to add a `when: nginx_version is not defined` to the [`ansible.builtin.set_fact`](https://github.com/nginxinc/ansible-role-nginx/blob/2d0843a22a5c580d29d25e1844aea453e2c8c117/tasks/opensource/install-source.yml#L328) task.

**Comment by alessfg** [comment]
The role now has this functionality thanks to @MohamedLamineAllal in #661!
