### ISSUE TITLE
Installing NGINX with modules

### ISSUE THREAD

**Issue by juanjoDiaz** [nginxinc/ansible-role-nginx#65]
In the documentation, the following modules are mentioned: njs,perl, waf, geoip, image_filter, rtmp and xslt

Unfortunately, I need the `ngx_http_auth_request_module`.
In the past, I've used the RPM `nginx-all-modules.noarch` package.

Could I achieve what I need using this role?
If not, is it in the roadmap to add the extra modules?

**Comment by alessfg** [comment]
Hi @juanjoDiaz! The `ngx_http_auth_request_module` is compiled by default in the NGINX package that this role installs. The additional module options included are the dynamic NGINX modules found here https://www.nginx.com/products/nginx/modules/. If the role doesn't work for you or you find some issues when trying to use some of the features from the `ngx_http_auth_request_module` please feel free to reopen or create a new issue!
