### ISSUE TITLE
AnsibleUndefinedVariable: dict object has no attribute html_file_location

### ISSUE THREAD

**Issue by bigstinky86** [nginxinc/ansible-role-nginx#73]
Hi,

I tried to run nginx role and it got failed on "(Setup: All NGINX) Dynamically Generate NGINX HTTP Configuration Files" task. I use example below from readme.

```---
- hosts: localhost
  become: true
  roles:
    - ansible-role-nginx
  vars:
    nginx_http_template_enable: true
    nginx_http_template:
      default:
        template_file: http/default.conf.j2
        conf_file_name: default.conf
        conf_file_location: /etc/nginx/conf.d/
        port: 80
        server_name: localhost
        error_page: /usr/share/nginx/html
        web_server:
          locations:
            default:
              location: /
              html_file_location: /usr/share/nginx/html
              html_file_name: index.html
```

But got an error AnsibleUndefinedVariable: dict object has no attribute html_file_location.

```failed: [localhost] (item={'value': {u'conf_file_name': u'default.conf', u'web_server': {u'locations': {u'default': {u'html_file_location': u'/usr/share/nginx/html', u'html_file_name': u'index.html', u'location': u'/'}}}, u'conf_file_location': u'/etc/nginx/conf.d/', u'server_name': u'localhost', u'template_file': u'http/default.conf.j2', u'error_page': u'/usr/share/nginx/html', u'port': 80}, 'key': u'default'}) => {
    "changed": false,
    "item": {
        "key": "default",
        "value": {
            "conf_file_location": "/etc/nginx/conf.d/",
            "conf_file_name": "default.conf",
            "error_page": "/usr/share/nginx/html",
            "port": 80,
            "server_name": "localhost",
            "template_file": "http/default.conf.j2",
            "web_server": {
                "locations": {
                    "default": {
                        "html_file_location": "/usr/share/nginx/html",
                        "html_file_name": "index.html",
                        "location": "/"
                    }
                }
            }
        }
    },
    "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'html_file_location'"
}```

**Comment by bigstinky86** [comment]
I use 0.9.0 role version

**Comment by bigstinky86** [comment]
I use 0.9.0 role version
ansible 2.7.2

**Comment by bigstinky86** [comment]
When execute role with parameters like below, then it passes without error

`hosts: localhost
become: true
roles:
    - ansible-role-nginx
vars:
    nginx_http_template_enable: true
    nginx_http_template:
      default:
        template_file: http/default.conf.j2
        conf_file_name: default.conf
        conf_file_location: /etc/nginx/conf.d/
        port: 80
        server_name: localhost
        error_page: /usr/share/nginx/html
        web_server:
            location: /
            html_file_location: /usr/share/nginx/html
            html_file_name: index.html`

**Comment by bigstinky86** [comment]
Probably something was wrong on my side. It works as expected.

**Comment by MaffooBristol** [comment]
I don't know what could've been the problem because you've not formatted your yml code, can you put three backticks around the code rather than one please? I'm having a similar error and this could be of use!

**Comment by alessfg** [comment]
@MaffooBristol can you post your playbook?

**Comment by alessfg** [comment]
Yup that could be it. And I also noticed an additional issue with the example in the README. I'll fix it asap. Thanks for helping out though! (And apologies you ran into such an unwarranted issue). Hopefully you'll reconsider giving this role another try in a few months when it's more stable!

**Comment by MaffooBristol** [comment]
Cool 😄

It still wasn't working when I fixed the indentation, but I couldn't really work out why. Is there also a way of doing proxy_pass without having to jump through all the load balancing hoops? Would be nice to see a bare-bones example of the proxy pass stuff

Thanks
Matt

**Comment by alessfg** [comment]
I have yet to test this, but for your example you could potentially get rid of the upstream group and do something like
```
vars:
  nginx_http_template_enable: true
  nginx_http_template:
    api_template:
      load_balancer:
        locations:
          api:
            location: /api
            proxy_pass: localhost:8080
```
On hindsight I do see how the load_balancer name is not the most descriptive for this particular section. I'll probably rename it to reverse_proxy to make it a little bit clearer what's going on.
