### ISSUE TITLE
SSL upload should support certificates and keys content

### ISSUE THREAD

**Issue by evilhamsterman** [nginxinc/ansible-role-nginx#83]
The SSL upload feature should support uploading content rather than just files. Sensitive data such as SSL keys should be stored in a secure method such as ansible-vault rather than as files.

**Comment by alessfg** [comment]
Would you like to submit a PR @evilhamsterman?

**Comment by evilhamsterman** [comment]
I may look at it in a bit, the other PRs I did were really quick this one
will take some more time.

**Comment by evilhamsterman** [comment]
I would add it to your backlog, if I get a chance I'll create a PR but don't count on it.

**Comment by evilhamsterman** [comment]
That would probably be a good idea. We use Hasicorp Vault to store and
deploy certificates

**Comment by evilhamsterman** [comment]
I looked into it and I see what you did it does work with Ansible vault because the copy module can auto decrypt vault encrypted files. However we use Hashicorp Vault to deploy our certificates which requires using a lookup filter to retrieve the content of the certs. Perhaps that is a bit beyond the scope of this module and maybe we should just close this.

**Comment by alessfg** [comment]
If anyone wants to take a stab at a PR to ensure that Vault works out of the box I'll look at it. Otherwise I think such an implementation is out the general scope of this role.
