### ISSUE TITLE
Clean conf.d before deploying new config

### ISSUE THREAD

**Issue by downingar** [nginxinc/ansible-role-nginx#93]
It would be very useful to have the option to delete all present files in the conf.d directory when deploying. Currently if one creates a config, but then changes it (and changes the name of the config file), the old one remains, making it difficult to remove old configs without being convoluted about it or doing so by hand. This would default to false, clearly, so as to retain backwards compatibility. It would seem that this would make the most sense to do at the same time as ensuring the respective conf directories exist.

**Comment by alessfg** [comment]
I agree @downingar. Great idea!
