### ISSUE TITLE
The role failes to get the ip address of the server

### ISSUE THREAD

**Issue by carlba** [nginxinc/ansible-role-nginx#96]
I recommend replacing 
```html
<p><span>Server address:</span> <span> {{ ansible_eth0.ipv4.address }} </span></p>
```
with 
```html
<p><span>Server address:</span> <span> {{ ansible_default_ipv4.address }} </span></p>
```
in `templates/www/index.html.j2`

Since the first network interface of a server might not always be called eth0

**Comment by alessfg** [comment]
This was already fixed in https://github.com/nginxinc/ansible-role-nginx/pull/90/files#diff-1e7638445a4b24f0a275fbe6012296eeR84 and will be available on Ansible Galaxy next release!

**Comment by carlba** [comment]
Sorry should have checked the previously reported issues!
